import type { PlaylistView, TrackView } from './TransitionsContract';

/**
 * The three playlists as Audius described them on 2026-09-02.
 *
 * Generated by `scripts/snapshot-transitions.ts`; do not edit by hand.
 * The channel starts on this so the first frame has real titles, and
 * the app falls back to it when Audius does not answer. See
 * `Catalogue` and `docs/TRANSITIONS_ROADMAP.md` D6.
 */
export const SNAPSHOT: {
  readonly playlists: readonly PlaylistView[];
  readonly tracks: Readonly<Record<string, readonly TrackView[]>>;
} = {
  playlists: [
    {
      id: '1',
      title: 'Deep House Vol.1',
      description: 'Deep House Vibes',
      curator: {
        name: 'DreamEater ',
        avatar: 'https://val006.open-audio-validator.com/content/01K8F0R79QZACF97G70878AGGS/150x150.jpg'
      },
      date: 'July 2025',
      plays: '96,690',
      time: '1h 38m',
      trackCount: 19,
      url: 'https://audius.co/Dreameaterism/playlist/deep-house-vol1'
    },
    {
      id: '2',
      title: 'Indie Rock Zone',
      description: 'Enjoy a variety of rock colours and flavours in the Indie Zone. Rock on!',
      curator: {
        name: 'STEVEE',
        avatar:
          'https://audius-figment-1-validator-19.figment.io/content/QmTwDu8V3KvQ1xUrpeRWXEeRtJ6ycbG9ABR2jnTPpCNmDb/150x150.jpg'
      },
      date: 'February 2023',
      plays: '119,356',
      time: '1h 3m',
      trackCount: 13,
      url: 'https://audius.co/steveeband/playlist/indie-rock-zone-469423842'
    },
    {
      id: '3',
      title: 'Classical Guitar',
      description: 'Classical Guitar',
      curator: {
        name: 'nasterblue',
        avatar:
          'https://val013.open-audio-validator.com/content/QmUMWKP2ZEUKea6Npza941r5yoJmcgzeptqPBiwiwdD6Ev/150x150.jpg'
      },
      date: 'April 2023',
      plays: '6,948',
      time: '42m',
      trackCount: 9,
      url: 'https://audius.co/nasterblue/playlist/classical-guitar-21448'
    }
  ],
  tracks: {
    '1': [
      {
        id: 'VgGb6',
        title: 'Wanna Be (Kiffer Cardenas Remix)',
        artist: 'Bordeø',
        duration: '4:33',
        seconds: 273,
        art: 'https://val014.open-audio-validator.com/content/QmWa29p9fKTJWUXXzwqGShEf7yatbHAwjWcLiCrvvMoBRQ/150x150.jpg',
        url: 'https://audius.co/Bordeo/wanna-be-kiffer-cardenas-remix',
        stream: 'https://api.audius.co/v1/tracks/VgGb6/stream?app_name=gesso-playground'
      },
      {
        id: 'ag3RE',
        title: 'Kumali - Run',
        artist: 'High Vibe Records',
        duration: '4:47',
        seconds: 287,
        art: 'https://audius-creator-11.theblueprint.xyz/content/QmR2c1YvwwuAnETUzUHvA1GLdVDqqfgD8hMNHo7UNXdezU/150x150.jpg',
        url: 'https://audius.co/highviberecords/kumali-run',
        stream: 'https://api.audius.co/v1/tracks/ag3RE/stream?app_name=gesso-playground'
      },
      {
        id: '63ZWkMG',
        title: 'broey. & notminimal. - 4u',
        artist: 'Broey.',
        duration: '3:19',
        seconds: 199,
        art: 'https://v.monophonic.digital/content/01J2C79RS2QJWSHW0QBVEQ0XME/150x150.jpg',
        url: 'https://audius.co/broeybeats/broey-notminimal-4u',
        stream: 'https://api.audius.co/v1/tracks/63ZWkMG/stream?app_name=gesso-playground'
      },
      {
        id: 'q72Zo',
        title: '05 - david duriez - under blister (album version)',
        artist: 'David Duriez',
        duration: '5:12',
        seconds: 312,
        art: 'https://audius-content-11.figment.io/content/Qmbp777dCuLCANBqbMQYZcwSzW9NaHJyu6nH6zDmAYuzDx/150x150.jpg',
        url: 'https://audius.co/davidduriez/05-david-duriez-under-blister-album-version-296329',
        stream: 'https://api.audius.co/v1/tracks/q72Zo/stream?app_name=gesso-playground'
      },
      {
        id: 'dRG0P',
        title: 'Ocean Eyes',
        artist: 'DreamEater ',
        duration: '7:15',
        seconds: 435,
        art: 'https://audius-creator-3.theblueprint.xyz/content/QmWeQz58mLyW8kajML2dxbu1tzpPQd2qL9A73PWxetrWNZ/150x150.jpg',
        url: 'https://audius.co/Dreameaterism/ocean-eyes-271170',
        stream: 'https://api.audius.co/v1/tracks/dRG0P/stream?app_name=gesso-playground'
      },
      {
        id: 'bQA4P',
        title: 'Tempation in My Head (Minimal dub mix)',
        artist: 'K 77',
        duration: '6:45',
        seconds: 405,
        art: 'https://audius-creator-6.theblueprint.xyz/content/QmQ4juzfUgnTeV6pPwhkD2WwiFZ39HkKaBC5bp33i7qJQX/150x150.jpg',
        url: 'https://audius.co/k77_artist/tempation-in-my-head-minimal-dub-mix-311947',
        stream: 'https://api.audius.co/v1/tracks/bQA4P/stream?app_name=gesso-playground'
      },
      {
        id: 'XP1rmkj',
        title: 'Wanted',
        artist: 'Broey.',
        duration: '3:38',
        seconds: 218,
        art: 'https://v.monophonic.digital/content/01HT3DYCFQZZN4GVBTWAM7RTYB/150x150.jpg',
        url: 'https://audius.co/broeybeats/wanted',
        stream: 'https://api.audius.co/v1/tracks/XP1rmkj/stream?app_name=gesso-playground'
      },
      {
        id: '5O5qM7M',
        title: 'Arrival',
        artist: 'Einmusik',
        duration: '7:15',
        seconds: 435,
        art: 'https://creatornode.audius.co/content/QmTkDBueWg3MBRHt1U5ZpEbftpSuZBRFNqeMfBHspaTTMJ/150x150.jpg',
        url: 'https://audius.co/einmusik_samuel/arrival',
        stream: 'https://api.audius.co/v1/tracks/5O5qM7M/stream?app_name=gesso-playground'
      },
      {
        id: 'YRv5y',
        title: 'Charesian - Euphoria',
        artist: 'Charesian',
        duration: '7:06',
        seconds: 426,
        art: 'https://audius-content-5.figment.io/content/QmTzLJQHTcy66tJYhGPVKxAbai8H1a2TRgYKigYJFgV3tP/150x150.jpg',
        url: 'https://audius.co/Charesian/charesian-euphoria',
        stream: 'https://api.audius.co/v1/tracks/YRv5y/stream?app_name=gesso-playground'
      },
      {
        id: 'ZO1g4',
        title: 'The Sea ',
        artist: 'Erkkulus',
        duration: '3:38',
        seconds: 218,
        art: 'https://v.monophonic.digital/content/Qmc3nkY18d4RCd6LznMqhsoVLsh8Ybvm848b85y5d3uuWa/150x150.jpg',
        url: 'https://audius.co/Erkkulus/the-sea--243412',
        stream: 'https://api.audius.co/v1/tracks/ZO1g4/stream?app_name=gesso-playground'
      },
      {
        id: '4A3YQ19',
        title: 'Broey., Almost Anyone - Falling (Almost Anyone Remix) ',
        artist: 'Broey.',
        duration: '6:36',
        seconds: 396,
        art: 'https://audius-nodes.com/content/01H73CY2R0DB0V9Z0M7KA87SE1/150x150.jpg',
        url: 'https://audius.co/broeybeats/broey-almost-anyone-falling-almost-anyone-remix',
        stream: 'https://api.audius.co/v1/tracks/4A3YQ19/stream?app_name=gesso-playground'
      },
      {
        id: 'gbW6W',
        title: 'DreamEater & Broken Blythe - The Truth',
        artist: 'DreamEater ',
        duration: '3:47',
        seconds: 227,
        art: 'https://v.monophonic.digital/content/QmW5rr3nHLZaEf9ACYq1HaQBDZPNMiqX4ntVDFLpYU6Uqx/150x150.jpg',
        url: 'https://audius.co/Dreameaterism/dreameater-broken-blythe-the-truth',
        stream: 'https://api.audius.co/v1/tracks/gbW6W/stream?app_name=gesso-playground'
      },
      {
        id: 'PQo7R',
        title: 'get me high [final]',
        artist: 'steve james',
        duration: '4:21',
        seconds: 261,
        art: 'https://audius-discovery-2.altego.net/content/QmRBMiXT9bcP2ZzD1D9k8nJeorm1eUeZMrNmXLajFq8FjF/150x150.jpg',
        url: 'https://audius.co/SteveJames/get-me-high-final-308245',
        stream: 'https://api.audius.co/v1/tracks/PQo7R/stream?app_name=gesso-playground'
      },
      {
        id: 'J50NY',
        title: "I'll Be Right There (Other Version)",
        artist: 'Øneheart',
        duration: '2:56',
        seconds: 176,
        art: 'https://audius-03.staked.cloud/content/QmWcunMaseVjLJjEKXaksT5jfhXVk7w34qgEHpM2j1JLyz/150x150.jpg',
        url: 'https://audius.co/oneheartmusic/ill-be-right-there-other-version-161251',
        stream: 'https://api.audius.co/v1/tracks/J50NY/stream?app_name=gesso-playground'
      },
      {
        id: '5K0Q1',
        title: 'Ben Böhmer, Nils Hoffmann & Malou - Breathing',
        artist: 'Anjunadeep',
        duration: '3:43',
        seconds: 223,
        art: 'https://v.monophonic.digital/content/QmT2YGTm5qyqmR1Zue7LcZ7qPNbKFTWmiY9vBHa8UWDGat/150x150.jpg',
        url: 'https://audius.co/anjunadeep/ben-böhmer-nils-hoffmann-malou-breathing-443390',
        stream: 'https://api.audius.co/v1/tracks/5K0Q1/stream?app_name=gesso-playground'
      },
      {
        id: 'oG9gR',
        title: 'Something Something Sunday Morning',
        artist: 'Captain Boomcake',
        duration: '6:00',
        seconds: 360,
        art: 'https://v.monophonic.digital/content/QmQ4wQzM5j5b6bMwZcW3eeAkhHvAUfSwTtUGdsLS3kmtH9/150x150.jpg',
        url: 'https://audius.co/CaptainBoomcake/something-something-sunday-morning-193739',
        stream: 'https://api.audius.co/v1/tracks/oG9gR/stream?app_name=gesso-playground'
      },
      {
        id: '4jvYd',
        title: 'Ekonovah - Wait A Minute',
        artist: 'Ekonovah',
        duration: '3:31',
        seconds: 211,
        art: 'https://v.monophonic.digital/content/QmNmm3xqBB3ckNRpsvX9RDUtFNEmmF9JD4QBnk5y3FyfJ4/150x150.jpg',
        url: 'https://audius.co/Ekonovah/ekonovah-wait-a-minute-145021',
        stream: 'https://api.audius.co/v1/tracks/4jvYd/stream?app_name=gesso-playground'
      },
      {
        id: 'QQmmR',
        title: 'Frano Fernandez - Camel ',
        artist: 'Frano Fernández',
        duration: '7:30',
        seconds: 450,
        art: 'https://audius-creator-14.theblueprint.xyz/content/QmZ7kyHSPcK2kPjghsLxkckrJzGRihDEKqm69mFABxKA5e/150x150.jpg',
        url: 'https://audius.co/FranoFernandez/frano-fernandez-camel',
        stream: 'https://api.audius.co/v1/tracks/QQmmR/stream?app_name=gesso-playground'
      },
      {
        id: 'V4wGB5P',
        title: ' AIR (Extended Mix) [NYX Music] Remix Contest',
        artist: 'Eli & Fur',
        duration: '5:56',
        seconds: 356,
        art: 'https://audius-content-7.figment.io/content/01JYH454D9X6KJX11B6WD3GRS4/150x150.jpg',
        url: 'https://audius.co/eliandfur/air-extended-mix-nyx-music-remix-contest',
        stream: 'https://api.audius.co/v1/tracks/V4wGB5P/stream?app_name=gesso-playground'
      }
    ],
    '2': [
      {
        id: '3512M',
        title: 'The Timing - Jason Kerrison',
        artist: 'Jason Kerrison',
        duration: '4:11',
        seconds: 251,
        art: 'https://val003.open-audio-validator.com/content/QmSogndo3paVS4tqw6kLCHGgifnZgXZHsXQJJVZEpJEDSq/150x150.jpg',
        url: 'https://audius.co/JasonKerrison/the-timing-jason-kerrison-443823',
        stream: 'https://api.audius.co/v1/tracks/3512M/stream?app_name=gesso-playground'
      },
      {
        id: 'y7dxE',
        title: 'All Of Your Senses',
        artist: 'Jason Kerrison',
        duration: '9:08',
        seconds: 548,
        art: 'https://audius-content-5.figment.io/content/QmWdR4Dp5DCDr1JE8Jx7TupAHxfbT4YjX76d5JSVHFfjDP/150x150.jpg',
        url: 'https://audius.co/JasonKerrison/all-of-your-senses-270335',
        stream: 'https://api.audius.co/v1/tracks/y7dxE/stream?app_name=gesso-playground'
      },
      {
        id: 'Xl8a5VR',
        title: 'Joyride',
        artist: 'STEVEE',
        duration: '3:51',
        seconds: 231,
        art: 'https://v.monophonic.digital/content/QmUHaNxAbRujorfgSpMJ5cJFB8JGaps7XhxaHNhMEqgNZG/150x150.jpg',
        url: 'https://audius.co/steveeband/joyride',
        stream: 'https://api.audius.co/v1/tracks/Xl8a5VR/stream?app_name=gesso-playground'
      },
      {
        id: 'NQMwx',
        title: 'Car Rock (with Oz Noy and Ian DaSouza)',
        artist: 'Jeremy Green',
        duration: '7:14',
        seconds: 434,
        art: 'https://v.monophonic.digital/content/QmewE5wnN7EVF2ZWHE9MbKWrrA87URbRGiW68gWRVFb5sF/150x150.jpg',
        url: 'https://audius.co/JeremyGreen/car-rock-with-oz-noy-and-ian-dasouza',
        stream: 'https://api.audius.co/v1/tracks/NQMwx/stream?app_name=gesso-playground'
      },
      {
        id: 'Yaw5r',
        title: 'Until The End',
        artist: 'Depths of Aetherium',
        duration: '5:01',
        seconds: 301,
        art: 'https://audius-content-4.figment.io/content/QmNNcYt2sZg1cFuAte4hdtYqQh5JPpmP7cpL2F2LioYGQ8/150x150.jpg',
        url: 'https://audius.co/frvgmentsband/until-the-end',
        stream: 'https://api.audius.co/v1/tracks/Yaw5r/stream?app_name=gesso-playground'
      },
      {
        id: 'v271V',
        title: 'Space Oddity - David Bowie (cover)',
        artist: 'Zunapalooza',
        duration: '5:23',
        seconds: 323,
        art: 'https://audius-creator-16.theblueprint.xyz/content/QmTfFvNRdN9nx1Vf5vNv4kzS7gZCHALPHJicRDQXJVZ1dW/150x150.jpg',
        url: 'https://audius.co/zunapalooza/space-oddity-david-bowie-cover-428758',
        stream: 'https://api.audius.co/v1/tracks/v271V/stream?app_name=gesso-playground'
      },
      {
        id: 'G5a2E',
        title: 'A Little Alien',
        artist: 'STEVEE',
        duration: '3:22',
        seconds: 202,
        art: 'https://audius-standardvc-1-validator-3.figment.io/content/QmRScyiJhFeernzzsqxbn9CynhhMh2874yaPgjzLXcvWGA/150x150.jpg',
        url: 'https://audius.co/steveeband/a-little-alien',
        stream: 'https://api.audius.co/v1/tracks/G5a2E/stream?app_name=gesso-playground'
      },
      {
        id: 'vJ2Ep',
        title: 'Ugochill - Beloved',
        artist: 'Ugochill Music',
        duration: '6:14',
        seconds: 374,
        art: 'https://v.monophonic.digital/content/QmYpaxh5krUTjzqkD7RHZ7mEgLVcf7255qHXoMZaPhqJiz/150x150.jpg',
        url: 'https://audius.co/ugochill/ugochill-beloved-352158',
        stream: 'https://api.audius.co/v1/tracks/vJ2Ep/stream?app_name=gesso-playground'
      },
      {
        id: '4k0EMj',
        title: 'Make Room',
        artist: 'winkandwoo',
        duration: '4:52',
        seconds: 292,
        art: 'https://val003.open-audio-validator.com/content/QmRVYNvd8ndWgLYA1GZwFUcUGiq5uyEfn6UESt3JrnYFBZ/150x150.jpg',
        url: 'https://audius.co/WINKANDW00/make-room',
        stream: 'https://api.audius.co/v1/tracks/4k0EMj/stream?app_name=gesso-playground'
      },
      {
        id: 'n0kd2',
        title: 'Lifeline',
        artist: 'The West View',
        duration: '4:12',
        seconds: 252,
        art: 'https://audius-content-3.figment.io/content/QmQicSqt2ac11HspXHfAeuM5sEsSNd64dA7cmERRkKpr3D/150x150.jpg',
        url: 'https://audius.co/thewestviewuk/lifeline-58266',
        stream: 'https://api.audius.co/v1/tracks/n0kd2/stream?app_name=gesso-playground'
      },
      {
        id: 'GEWBE',
        title: 'Halitosis',
        artist: 'Chris Landis',
        duration: '3:07',
        seconds: 187,
        art: 'https://v.monophonic.digital/content/QmcBeruGABLhyuifAQuo9kHZ7pc9gRpFf1tznJfYGyobTx/150x150.jpg',
        url: 'https://audius.co/ChrisLandis/halitosis-219518',
        stream: 'https://api.audius.co/v1/tracks/GEWBE/stream?app_name=gesso-playground'
      },
      {
        id: 'aZ4oWBo',
        title: 'Get It Right',
        artist: 'STEVEE',
        duration: '2:44',
        seconds: 164,
        art: 'https://v.monophonic.digital/content/QmT34PSbWovyKKgnJgCicwWy4cBz7JZ1Zuqk4rZMmy3DMZ/150x150.jpg',
        url: 'https://audius.co/steveeband/get-it-right',
        stream: 'https://api.audius.co/v1/tracks/aZ4oWBo/stream?app_name=gesso-playground'
      },
      {
        id: 'QJpGKw',
        title: '🖤YAN MI - HELLO',
        artist: ' YAN MI 🌕 🧬🩻👾',
        duration: '3:12',
        seconds: 192,
        art: 'https://val013.open-audio-validator.com/content/QmbNoMPLkP93YTKGKsN8CX89ccNdthFAiCWNFNRUkfMwr9/150x150.jpg',
        url: 'https://audius.co/yanmi/🖤yan-mi-hello',
        stream: 'https://api.audius.co/v1/tracks/QJpGKw/stream?app_name=gesso-playground'
      }
    ],
    '3': [
      {
        id: 'xdy27',
        title: 'Che Sara Guitar',
        artist: 'nasterblue',
        duration: '5:22',
        seconds: 322,
        art: 'https://audius-nodes.com/content/QmRB9rQ5DbFiRALm3XQzb91ffLvHPj19Ptc1RdQ1iUuRzt/150x150.jpg',
        url: 'https://audius.co/nasterblue/che-sara-guitar-186031',
        stream: 'https://api.audius.co/v1/tracks/xdy27/stream?app_name=gesso-playground'
      },
      {
        id: 'X6blJ',
        title: 'Thiên Thiên Khuyết Ca (千千阙歌) ',
        artist: 'nasterblue',
        duration: '4:02',
        seconds: 242,
        art: 'https://audius-nodes.com/content/QmRB9rQ5DbFiRALm3XQzb91ffLvHPj19Ptc1RdQ1iUuRzt/150x150.jpg',
        url: 'https://audius.co/nasterblue/thiên-thiên-khuyết-ca-千千阙歌--186024',
        stream: 'https://api.audius.co/v1/tracks/X6blJ/stream?app_name=gesso-playground'
      },
      {
        id: '80OPJ',
        title: 'Recuerdos de la alhambra',
        artist: 'nasterblue',
        duration: '2:36',
        seconds: 156,
        art: 'https://audius-content-13.figment.io/content/QmRB9rQ5DbFiRALm3XQzb91ffLvHPj19Ptc1RdQ1iUuRzt/150x150.jpg',
        url: 'https://audius.co/nasterblue/recuerdos-de-la-alhambra-186032',
        stream: 'https://api.audius.co/v1/tracks/80OPJ/stream?app_name=gesso-playground'
      },
      {
        id: 'rGy7g',
        title: 'Yuki No Hana・Snow Flower',
        artist: 'nasterblue',
        duration: '5:44',
        seconds: 344,
        art: 'https://audius-content-13.figment.io/content/QmRB9rQ5DbFiRALm3XQzb91ffLvHPj19Ptc1RdQ1iUuRzt/150x150.jpg',
        url: 'https://audius.co/nasterblue/yuki-no-hana・snow-flower-186030',
        stream: 'https://api.audius.co/v1/tracks/rGy7g/stream?app_name=gesso-playground'
      },
      {
        id: 'qZy7a',
        title: 'Canon in D - Pachelbel',
        artist: 'nasterblue',
        duration: '3:08',
        seconds: 188,
        art: 'https://audius-content-13.figment.io/content/QmRB9rQ5DbFiRALm3XQzb91ffLvHPj19Ptc1RdQ1iUuRzt/150x150.jpg',
        url: 'https://audius.co/nasterblue/canon-in-d-pachelbel-186029',
        stream: 'https://api.audius.co/v1/tracks/qZy7a/stream?app_name=gesso-playground'
      },
      {
        id: 'E0Y7R',
        title: 'Hotel California',
        artist: 'nasterblue',
        duration: '6:38',
        seconds: 398,
        art: 'https://v.monophonic.digital/content/QmRB9rQ5DbFiRALm3XQzb91ffLvHPj19Ptc1RdQ1iUuRzt/150x150.jpg',
        url: 'https://audius.co/nasterblue/hotel-california-186027',
        stream: 'https://api.audius.co/v1/tracks/E0Y7R/stream?app_name=gesso-playground'
      },
      {
        id: 'd0GR2',
        title: 'Careless Whisper - George Michael',
        artist: 'nasterblue',
        duration: '5:12',
        seconds: 312,
        art: 'https://v.monophonic.digital/content/QmRB9rQ5DbFiRALm3XQzb91ffLvHPj19Ptc1RdQ1iUuRzt/150x150.jpg',
        url: 'https://audius.co/nasterblue/careless-whisper-george-michael-186026',
        stream: 'https://api.audius.co/v1/tracks/d0GR2/stream?app_name=gesso-playground'
      },
      {
        id: 'X6blJ',
        title: 'Thiên Thiên Khuyết Ca (千千阙歌) ',
        artist: 'nasterblue',
        duration: '4:02',
        seconds: 242,
        art: 'https://audius-nodes.com/content/QmRB9rQ5DbFiRALm3XQzb91ffLvHPj19Ptc1RdQ1iUuRzt/150x150.jpg',
        url: 'https://audius.co/nasterblue/thiên-thiên-khuyết-ca-千千阙歌--186024',
        stream: 'https://api.audius.co/v1/tracks/X6blJ/stream?app_name=gesso-playground'
      },
      {
        id: 'yg927',
        title: 'Mưa Trên Cuộc Tình - 珍惜',
        artist: 'nasterblue',
        duration: '4:57',
        seconds: 297,
        art: 'https://audius-nodes.com/content/QmRB9rQ5DbFiRALm3XQzb91ffLvHPj19Ptc1RdQ1iUuRzt/150x150.jpg',
        url: 'https://audius.co/nasterblue/mưa-trên-cuộc-tình-珍惜-186035',
        stream: 'https://api.audius.co/v1/tracks/yg927/stream?app_name=gesso-playground'
      }
    ]
  }
};
