// API report for @gesso/devtools.
//
// Generated by `pnpm api:update` from the declarations tsdown emits, with
// comments stripped and chunk hashes normalised. Committed so that a change
// to the public surface is a reviewable diff. Do not edit by hand.

// ==== index.d.ts ====
import {
  FrameMetrics,
  RuntimeErrorSource,
  UiFramePhase,
  UiNodeReport
} from "@gesso/framework";
interface SourceMapV3 {
  version: number;
  file?: string;
  sourceRoot?: string;
  sources: (string | null)[];
  sourcesContent?: (string | null)[];
  names?: string[];
  mappings: string;
}
interface OriginalPosition {
  source: string;
  line: number;
  column: number;
}
type Segment = [generatedColumn: number, sourceIndex: number, sourceLine: number, sourceColumn: number];
declare function decodeMappings(mappings: string): Segment[][];
declare class SourceMapConsumer {
  private readonly lines;
  private readonly sources;
  private readonly contents;
  constructor(map: SourceMapV3);
  lookup(line: number, column: number): OriginalPosition | null;
  contentFor(source: string): string | null;
}
declare function parseSourceMappingUrl(script: string): string | null;
declare class SourceMapStore {
  private readonly cache;
  private readonly load;
  constructor(load?: (url: string) => Promise<string>);
  consumerFor(scriptUrl: string): Promise<SourceMapConsumer | null>;
  private resolve;
}
type ErrorOrigin = RuntimeErrorSource | 'window';
interface ErrorOverlayOptions {
  echoToConsole?: boolean;
  sourceMaps?: SourceMapStore;
}
declare class ErrorOverlay {
  private readonly host;
  private readonly doc;
  private readonly view;
  private readonly container;
  private readonly root;
  private readonly panel;
  private readonly maps;
  private readonly echo;
  private readonly entries;
  private readonly restoreHostPosition;
  private shown;
  private disposed;
  private detachWindow;
  constructor(host: HTMLElement, options?: ErrorOverlayOptions);
  get count(): number;
  get visible(): boolean;
  report: (message: string, stack?: string, origin?: ErrorOrigin) => void;
  reportError: (error: unknown, origin?: ErrorOrigin) => void;
  captureWindowErrors(target?: Window | null): () => void;
  hide(): void;
  clear(): void;
  dispose(): void;
  private show;
  private handleKeyDown;
  private resolveSources;
  private el;
  private button;
  private render;
  private step;
  private copy;
}
declare function mountErrorOverlay(host: HTMLElement, options?: ErrorOverlayOptions): ErrorOverlay;
interface NodeInspector {
  set(report: UiNodeReport | null): void;
  dispose(): void;
}
interface NodeInspectorOptions {
  readonly corner?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
}
declare function mountNodeInspector(host: HTMLElement, options?: NodeInspectorOptions): NodeInspector;
interface FrameProfiler {
  report(metrics: FrameMetrics): void;
  setVisible(visible: boolean): void;
  readonly visible: boolean;
  dispose(): void;
}
interface FrameProfilerOptions {
  readonly history?: number;
  readonly redrawMs?: number;
  readonly corner?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
}
interface FrameSample {
  readonly phases: Readonly<Record<UiFramePhase, number>>;
  readonly total: number;
  readonly gap: number;
  readonly input: number | null;
}
declare function mountFrameProfiler(host: HTMLElement, options?: FrameProfilerOptions): FrameProfiler;
interface FrameSummary {
  readonly fps: number;
  readonly meanTotal: number;
  readonly worstTotal: number;
  readonly worstGap: number;
  readonly worstInput: number | null;
  readonly worstPhase: Record<UiFramePhase, number>;
}
declare function summarize(samples: readonly FrameSample[]): FrameSummary;
interface CodeFrameLine {
  number: number;
  text: string;
  target: boolean;
}
interface CodeFrame {
  lines: CodeFrameLine[];
  column: number;
}
declare function codeFrame(source: string, line: number, column: number, context?: number): CodeFrame | null;
interface StackLocation {
  url: string;
  line: number;
  column: number;
}
interface StackFrame {
  raw: string;
  fn: string | null;
  location: StackLocation | null;
  original: OriginalPosition | null;
}
declare function parseStack(stack: string): StackFrame[];
declare function mapStack(frames: StackFrame[], store: SourceMapStore): Promise<StackFrame[]>;
declare function primaryFrame(frames: StackFrame[]): StackFrame | null;
declare function shortenPath(url: string, origin?: string): string;
declare function formatFrame(frame: StackFrame, origin?: string): string;
export {
  codeFrame,
  decodeMappings,
  ErrorOverlay,
  formatFrame,
  mapStack,
  mountErrorOverlay,
  mountFrameProfiler,
  mountNodeInspector,
  parseSourceMappingUrl,
  parseStack,
  primaryFrame,
  shortenPath,
  SourceMapConsumer,
  SourceMapStore,
  summarize,
  type CodeFrame,
  type CodeFrameLine,
  type ErrorOrigin,
  type ErrorOverlayOptions,
  type FrameProfiler,
  type FrameProfilerOptions,
  type FrameSample,
  type FrameSummary,
  type NodeInspector,
  type NodeInspectorOptions,
  type OriginalPosition,
  type SourceMapV3,
  type StackFrame,
  type StackLocation
};
