// API report for gesso-devtools.
//
// Generated by `pnpm api:update` from the declarations tsdown emits, with
// comments stripped and chunk hashes normalised. Committed so that a change
// to the public surface is a reviewable diff. Do not edit by hand.

// ==== index.d.ts ====
import {
  ActionCause,
  ActionEntry,
  ChannelErrorEntry,
  ChannelPort,
  CommandEntry,
  DevtoolsEvent,
  DevtoolsRequest,
  FrameEntry,
  FrameMetrics,
  PatchEntry,
  RuntimeErrorSource,
  ShellToRuntimeMessage,
  UiFramePhase,
  UiNodeReport,
  UiTreeNode,
  WorkerHandle
} from "gesso-framework";
interface SourceMapV3 {
  version: number;
  file?: string;
  sourceRoot?: string;
  sources: (string | null)[];
  sourcesContent?: (string | null)[];
  names?: string[];
  mappings: string;
}
interface OriginalPosition {
  source: string;
  line: number;
  column: number;
  content?: string | null;
}
type Segment = [generatedColumn: number, sourceIndex: number, sourceLine: number, sourceColumn: number];
declare function decodeMappings(mappings: string): Segment[][];
declare class SourceMapConsumer {
  private readonly lines;
  private readonly sources;
  private readonly contents;
  constructor(map: SourceMapV3);
  lookup(line: number, column: number): OriginalPosition | null;
  contentFor(source: string): string | null;
}
declare function parseSourceMappingUrl(script: string): string | null;
declare class SourceMapStore {
  private readonly cache;
  private readonly load;
  constructor(load?: (url: string) => Promise<string>);
  consumerFor(scriptUrl: string): Promise<SourceMapConsumer | null>;
  originalFor(scriptUrl: string, line: number, column: number, depth?: number): Promise<OriginalPosition | null>;
  private resolve;
}
type ErrorOrigin = RuntimeErrorSource | 'window';
interface ErrorOverlayOptions {
  echoToConsole?: boolean;
  sourceMaps?: SourceMapStore;
}
declare class ErrorOverlay {
  private readonly host;
  private readonly doc;
  private readonly view;
  private readonly container;
  private readonly root;
  private readonly panel;
  private readonly maps;
  private readonly echo;
  private readonly entries;
  private readonly restoreHostPosition;
  private shown;
  private disposed;
  private detachWindow;
  constructor(host: HTMLElement, options?: ErrorOverlayOptions);
  get count(): number;
  get visible(): boolean;
  report: (message: string, stack?: string, origin?: ErrorOrigin) => void;
  reportError: (error: unknown, origin?: ErrorOrigin) => void;
  captureWindowErrors(target?: Window | null): () => void;
  hide(): void;
  clear(): void;
  dispose(): void;
  private show;
  private handleKeyDown;
  private resolveSources;
  private el;
  private button;
  private render;
  private step;
  private copy;
}
declare function mountErrorOverlay(host: HTMLElement, options?: ErrorOverlayOptions): ErrorOverlay;
interface ActionLog {
  tap(handle: WorkerHandle, tokens: readonly ActionLogToken[]): WorkerHandle;
  tapPort(port: ChannelPort, token: ActionLogToken): ChannelPort;
  cause(label: string): () => void;
  frame(id: number): void;
  readonly entries: readonly ActionEntry[];
  readonly channels: readonly string[];
  readonly pinnedTo: number | null;
  jumpTo(seq: number | null): void;
  clear(): void;
  subscribe(listener: () => void): () => void;
  dispose(): void;
}
interface ActionLogToken {
  readonly name: string;
  readonly initial: object;
}
interface ActionLogOptions {
  readonly limit?: number;
}
declare function createActionLog(options?: ActionLogOptions): ActionLog;
declare function forwardNewEntries(log: ActionLog, send: (entry: ActionEntry) => void): () => void;
interface ActionLogPanel {
  setVisible(visible: boolean): void;
  readonly visible: boolean;
  dispose(): void;
}
interface ActionLogPanelOptions {
  readonly corner?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
}
declare function mountActionLogPanel(host: HTMLElement, log: ActionLog, options?: ActionLogPanelOptions): ActionLogPanel;
declare function actionGlyph(entry: ActionEntry): string;
declare function describeActionEntry(entry: ActionEntry): string;
interface RenderWorkerHost {
  onmessage: ((event: {
    data: unknown;
  }) => void) | null;
  postMessage(message: unknown, transfer?: Transferable[]): void;
}
interface RenderWorkerTapOptions {
  readonly host?: RenderWorkerHost;
  readonly forward?: boolean;
}
interface RenderWorkerTap {
  applicationWorker(tokens: readonly ActionLogToken[]): WorkerHandle;
  dispose(): void;
}
declare function tapRenderWorker(log: ActionLog, options?: RenderWorkerTapOptions): RenderWorkerTap;
declare function inputLabel(message: ShellToRuntimeMessage | undefined): string | null;
interface NodePickerOptions {
  readonly host: EventTarget;
  hovered(): string | null;
}
interface DevtoolsPicker {
  setEnabled(enabled: boolean): void;
  readonly enabled: boolean;
  onPick(listener: ((id: string) => void) | null): void;
  dispose(): void;
}
declare function createNodePicker(options: NodePickerOptions): DevtoolsPicker;
interface NodeReportViewOptions {
  onEditProp?(name: string, value: unknown): void;
}
declare function renderNodeReport(doc: Document, report: UiNodeReport, options?: NodeReportViewOptions): HTMLElement[];
declare const NODE_REPORT_STYLES = "\nh1 { margin: 0 0 6px; font-size: 12px; color: var(--gd-accent, #79c0ff); overflow-wrap: anywhere; }\nh2 {\n  margin: 10px 0 4px;\n  font-size: 10px;\n  text-transform: uppercase;\n  letter-spacing: 0.08em;\n  color: var(--gd-muted, #8b949e);\n}\np { margin: 0 0 2px; }\n.label { color: var(--gd-muted, #8b949e); }\n.rows { display: grid; grid-template-columns: auto 1fr; gap: 0 8px; margin: 0; }\ndt { color: var(--gd-muted, #8b949e); overflow-wrap: anywhere; }\ndt.modifier { color: var(--gd-purple, #d2a8ff); }\ndt.binding { color: var(--gd-green, #7ee787); }\ndt.provided { color: var(--gd-orange, #ffa657); }\ndd { margin: 0; overflow-wrap: anywhere; }\ndd.editable { cursor: pointer; border-radius: 3px; }\ndd.editable:hover { background: var(--gd-bg-hover, #21262d); }\n.edit {\n  width: 100%;\n  box-sizing: border-box;\n  border: 1px solid var(--gd-accent, #79c0ff);\n  border-radius: 3px;\n  padding: 0 3px;\n  background: var(--gd-bg, #0d1117);\n  color: var(--gd-text, #e6edf3);\n  font: inherit;\n}\n.note { color: var(--gd-faint, #6e7681); }\n.stream { display: block; color: var(--gd-green, #7ee787); }\n.explanation { margin: 0; white-space: pre-wrap; overflow-wrap: anywhere; color: var(--gd-text-strong, #c9d1d9); }\n";
interface DevtoolsAppInfo {
  readonly id: string;
  readonly name: string;
}
type PageMessage =
{
  type: 'apps';
  apps: readonly DevtoolsAppInfo[];
} | {
  type: 'event';
  app: string;
  event: DevtoolsEvent;
} |
{
  type: 'action';
  app: string;
  entry: ActionEntry;
} |
{
  type: 'picked';
  app: string;
  id: string;
};
type PanelMessage =
{
  type: 'hello';
} | {
  type: 'request';
  app: string;
  request: DevtoolsRequest;
} |
{
  type: 'pick';
  app: string;
  enabled: boolean;
};
interface DevtoolsPort<In, Out> {
  post(message: Out): void;
  onMessage(listener: (message: In) => void): () => void;
  close(): void;
}
type PagePort = DevtoolsPort<PanelMessage, PageMessage>;
type PanelPort = DevtoolsPort<PageMessage, PanelMessage>;
declare function createDirectPorts(): {
  page: PagePort;
  panel: PanelPort;
};
interface Envelope<T> {
  readonly source: typeof ENVELOPE_SOURCE;
  readonly to: 'page' | 'panel';
  readonly message: T;
}
declare const ENVELOPE_SOURCE = "gesso-devtools";
declare function isEnvelope(value: unknown, to: 'page' | 'panel'): value is Envelope<unknown>;
interface WindowLike {
  addEventListener(type: 'message', listener: (event: {
    data: unknown;
    source?: unknown;
  }) => void): void;
  removeEventListener(type: 'message', listener: (event: {
    data: unknown;
    source?: unknown;
  }) => void): void;
  postMessage(message: unknown, targetOrigin: string): void;
  readonly location?: {
    readonly origin: string;
  };
}
declare function windowPagePort(win: WindowLike): PagePort;
declare function windowPanelPort(win: WindowLike): PanelPort;
interface DevtoolsApp {
  devtools(request: DevtoolsRequest): void;
  onDevtools(listener: ((event: DevtoolsEvent) => void) | null): void;
}
interface ConnectDevtoolsOptions {
  readonly name?: string;
  readonly actions?: ActionLog;
  readonly picker?: DevtoolsPicker;
  readonly window?: (WindowLike & HookHost) | null;
}
interface DevtoolsHook {
  readonly apps: readonly DevtoolsAppInfo[];
  register(app: DevtoolsApp, options?: Omit<ConnectDevtoolsOptions, 'window'>): () => void;
  attach(port: PagePort): () => void;
}
declare const HOOK_PROPERTY = "__GESSO_DEVTOOLS__";
interface HookHost {
  [HOOK_PROPERTY]?: DevtoolsHook;
}
declare function getDevtoolsHook(win?: (WindowLike & HookHost) | null): DevtoolsHook;
declare function connectDevtools(app: DevtoolsApp, options?: ConnectDevtoolsOptions): () => void;
interface DevtoolsPanel {
  readonly app: DevtoolsAppInfo | null;
  show(appId: string): void;
  setTheme(theme: DevtoolsPanelTheme): void;
  dispose(): void;
}
type DevtoolsPanelTheme = 'light' | 'dark' | 'auto';
interface DevtoolsPanelOptions {
  readonly theme?: DevtoolsPanelTheme;
  readonly openDepth?: number;
  readonly consoleLimit?: number;
  readonly actionLimit?: number;
}
declare function mountDevtoolsPanel(host: HTMLElement, port: PanelPort, options?: DevtoolsPanelOptions): DevtoolsPanel;
interface TreeRow {
  readonly node: UiTreeNode;
  readonly depth: number;
  readonly expandable: boolean;
  readonly expanded: boolean;
  readonly owner?: string;
}
declare function treeRows(root: UiTreeNode, expanded: ReadonlySet<string>): TreeRow[];
declare function idsToDepth(root: UiTreeNode, depth: number): string[];
declare function pathTo(root: UiTreeNode, id: string): string[] | null;
declare function rowLabel(row: TreeRow): string;
interface NodeInspector {
  set(report: UiNodeReport | null): void;
  dispose(): void;
}
interface NodeInspectorOptions {
  readonly corner?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
}
declare function mountNodeInspector(host: HTMLElement, options?: NodeInspectorOptions): NodeInspector;
interface FrameProfiler {
  report(metrics: FrameMetrics): void;
  setVisible(visible: boolean): void;
  readonly visible: boolean;
  dispose(): void;
}
interface FrameProfilerOptions {
  readonly history?: number;
  readonly redrawMs?: number;
  readonly corner?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
  readonly layout?: 'floating' | 'docked';
}
interface FrameSample {
  readonly phases: Readonly<Record<UiFramePhase, number>>;
  readonly total: number;
  readonly gap: number;
  readonly input: number | null;
}
declare function mountFrameProfiler(host: HTMLElement, options?: FrameProfilerOptions): FrameProfiler;
interface FrameSummary {
  readonly fps: number;
  readonly meanTotal: number;
  readonly worstTotal: number;
  readonly worstGap: number;
  readonly worstInput: number | null;
  readonly worstPhase: Record<UiFramePhase, number>;
}
declare function summarize(samples: readonly FrameSample[]): FrameSummary;
interface CodeFrameLine {
  number: number;
  text: string;
  target: boolean;
}
interface CodeFrame {
  lines: CodeFrameLine[];
  column: number;
}
declare function codeFrame(source: string, line: number, column: number, context?: number): CodeFrame | null;
interface StackLocation {
  url: string;
  line: number;
  column: number;
}
interface StackFrame {
  raw: string;
  fn: string | null;
  location: StackLocation | null;
  original: OriginalPosition | null;
}
declare function parseStack(stack: string): StackFrame[];
declare function mapStack(frames: StackFrame[], store: SourceMapStore): Promise<StackFrame[]>;
declare function primaryFrame(frames: StackFrame[]): StackFrame | null;
declare function shortenPath(url: string, origin?: string): string;
declare function formatFrame(frame: StackFrame, origin?: string): string;
export {
  actionGlyph,
  codeFrame,
  connectDevtools,
  createActionLog,
  createDirectPorts,
  createNodePicker,
  decodeMappings,
  describeActionEntry,
  ENVELOPE_SOURCE,
  ErrorOverlay,
  formatFrame,
  forwardNewEntries,
  getDevtoolsHook,
  HOOK_PROPERTY,
  idsToDepth,
  inputLabel,
  isEnvelope,
  mapStack,
  mountActionLogPanel,
  mountDevtoolsPanel,
  mountErrorOverlay,
  mountFrameProfiler,
  mountNodeInspector,
  NODE_REPORT_STYLES,
  parseSourceMappingUrl,
  parseStack,
  pathTo,
  primaryFrame,
  renderNodeReport,
  rowLabel,
  shortenPath,
  SourceMapConsumer,
  SourceMapStore,
  summarize,
  tapRenderWorker,
  treeRows,
  type ActionCause,
  type ActionEntry,
  type ActionLog,
  type ActionLogOptions,
  type ActionLogPanel,
  type ActionLogPanelOptions,
  type ActionLogToken,
  type ChannelErrorEntry,
  type CodeFrame,
  type CodeFrameLine,
  type CommandEntry,
  type ConnectDevtoolsOptions,
  type DevtoolsApp,
  type DevtoolsAppInfo,
  type DevtoolsHook,
  type DevtoolsPanel,
  type DevtoolsPanelOptions,
  type DevtoolsPanelTheme,
  type DevtoolsPicker,
  type DevtoolsPort,
  type Envelope,
  type ErrorOrigin,
  type ErrorOverlayOptions,
  type FrameEntry,
  type FrameProfiler,
  type FrameProfilerOptions,
  type FrameSample,
  type FrameSummary,
  type HookHost,
  type NodeInspector,
  type NodeInspectorOptions,
  type NodePickerOptions,
  type NodeReportViewOptions,
  type OriginalPosition,
  type PageMessage,
  type PagePort,
  type PanelMessage,
  type PanelPort,
  type PatchEntry,
  type RenderWorkerHost,
  type RenderWorkerTap,
  type RenderWorkerTapOptions,
  type SourceMapV3,
  type StackFrame,
  type StackLocation,
  type TreeRow,
  type WindowLike,
  windowPagePort,
  windowPanelPort
};
