// API report for @gesso/framework.
//
// Generated by `pnpm api:update` from the declarations tsdown emits, with
// comments stripped and chunk hashes normalised. Committed so that a change
// to the public surface is a reviewable diff. Do not edit by hand.

// ==== FunctionComponent.d.ts ====
import {
  BehaviorSubject,
  Observable
} from "rxjs";
import {
  Reactive,
  UiChild
} from "@gesso/core";
declare abstract class Component {
  onMount?(): void;
  onUnmount?(): void;
  abstract render(): UiChild;
}
declare class InputCell<T> extends BehaviorSubject<T> {
  label: string | undefined;
  private snapshotBy;
  private warnedStale;
  private emitted;
  constructor(initialValue: T);
  emit(...args: EmitArgs<T>): void;
  get events(): Observable<EmitValue<T>>;
  get value(): T;
  next(value: T): void;
}
interface ReadableCell<T> extends Observable<T> {
  readonly value: T;
}
declare function input<T>(initialValue: T): InputCell<T>;
declare function input<T>(source: InputCell<T | undefined>, fallback: T): InputCell<T>;
type EmitArgs<T> = NonNullable<T> extends ((...args: infer A) => void) ? A : never;
type EmitValue<T> = NonNullable<T> extends ((first: infer V, ...rest: never[]) => void) ? V : void;
type OutputCell<A extends unknown[]> = InputCell<((...args: A) => void) | undefined>;
declare function output<A extends unknown[]>(): OutputCell<A>;
declare const OUTPUT_TARGET: unique symbol;
interface OutputTarget<V> {
  readonly [OUTPUT_TARGET]: {
    next(value: V): void;
  };
}
declare function into<V>(target: {
  next(value: V): void;
}): OutputTarget<V>;
declare function isOutputTarget(value: unknown): value is OutputTarget<unknown>;
type Command = (...args: never[]) => void;
type CommandMap = Record<string, Command>;
interface ChannelToken<View extends object, Commands extends object = Record<string, never>> {
  readonly name: string;
  readonly initial: View;
  readonly commands?: Commands;
}
declare function channel<View extends object, Commands extends object = Record<string, never>>(name: string, initial: View): ChannelToken<View, Commands>;
declare function viewKeys(token: {
  initial: object;
}): string[];
type PatchPath = readonly (string | number)[];
type Patch = {
  op: 'set';
  projection: string;
  path: PatchPath;
  value: unknown;
} | {
  op: 'delete';
  projection: string;
  path: PatchPath;
} | {
  op: 'splice';
  projection: string;
  path: PatchPath;
  index: number;
  deleteCount: number;
  items: readonly unknown[];
};
declare function diffProjection(projection: string, previous: unknown, current: unknown): Patch[];
declare function applyPatches(root: unknown, patches: readonly Patch[]): unknown;
declare function applyPatch(root: unknown, patch: Patch): unknown;
interface ChannelPort {
  postMessage(message: unknown): void;
  onmessage: ((event: {
    data: unknown;
  }) => void) | null;
}
type ChannelClientMessage = {
  type: 'channel:sync';
} | {
  type: 'channel:command';
  command: string;
  payload: unknown;
};
type ChannelHostMessage = {
  type: 'channel:patch';
  patches: Patch[];
} | {
  type: 'channel:error';
  message: string;
  stack?: string;
};
declare function isChannelClientMessage(value: unknown): value is ChannelClientMessage;
declare function isChannelHostMessage(value: unknown): value is ChannelHostMessage;
declare class ChannelReplica<View extends object, Commands extends object> {
  private readonly token;
  private readonly port;
  private readonly cells;
  private readonly commandProxy;
  private errorListener;
  private pending;
  private scheduleFlush;
  constructor(token: ChannelToken<View, Commands>, port: ChannelPort);
  get view(): { readonly [K in keyof View]: InputCell<View[K]>; };
  get send(): Commands;
  private readonly viewProxy;
  private readonly warnedArity;
  private createCommandProxy;
  onError(listener: ((message: string, stack?: string) => void) | null): void;
  private receive;
  private report;
  deferPatches(scheduleFlush: () => void): void;
  get hasPendingPatches(): boolean;
  flush(): void;
  applyPatches(patches: readonly Patch[]): void;
  private post;
  dispose(): void;
}
interface ComponentContext {
  inject<S extends object>(ServiceClass: new () => S): S;
  channel<V extends object, C extends object>(token: ChannelToken<V, C>): ChannelReplica<V, C>;
  onMount(hook: () => void): void;
  onUnmount(hook: () => void): void;
}
type Inputs<P> = { readonly [K in keyof P]-?: InputCell<P[K]>; };
type FunctionComponent<P = {}> = (props: Inputs<P>, context: ComponentContext) => UiChild;
type ClassComponent = new () => Component;
type ComponentType = ClassComponent | ((props: any, context: ComponentContext) => UiChild);
type IsAny<T> = 0 extends 1 & T ? true : false;
type CellValue<C> = C extends InputCell<infer T> ? T : never;
type OptionalCellKeys<I> = { [K in keyof I]: undefined extends CellValue<I[K]> ? K : never; }[keyof I];
type PropsForCells<I> = [keyof I] extends [never] ? NoProps : { [K in OptionalCellKeys<I>]?: Passable<CellValue<I[K]>>; } & { [K in Exclude<keyof I, OptionalCellKeys<I>>]: Passable<CellValue<I[K]>>; };
type Passable<T> = NonNullable<T> extends ((first: infer V, ...rest: never[]) => void) ? Reactive<T> | OutputTarget<V> : Reactive<T>;
type NoProps = {
  readonly __noProps?: never;
};
type InputFields<I> = { [K in keyof I as I[K] extends InputCell<any> ? K : never]: I[K]; };
type ComponentProps<C> = C extends ClassComponent ? Partial<PropsForCells<InputFields<InstanceType<C>>>> : C extends ((props: infer I, ...rest: any[]) => UiChild) ? IsAny<I> extends true ? Record<string, unknown> : unknown extends I ? NoProps : [I] extends [undefined] ? NoProps : PropsForCells<I> : never;
type RequiredKeys<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? never : K; }[keyof T];
type ComponentArgs<C> = RequiredKeys<ComponentProps<C>> extends never ? [props?: ComponentProps<C>, key?: string | number] : [props: ComponentProps<C>, key?: string | number];
declare function isClassComponent(component: ComponentType): component is ClassComponent;
export {
  applyPatch,
  applyPatches,
  channel,
  ChannelClientMessage,
  ChannelHostMessage,
  ChannelPort,
  ChannelReplica,
  ChannelToken,
  ClassComponent,
  Command,
  CommandMap,
  Component,
  ComponentArgs,
  ComponentContext,
  ComponentProps,
  ComponentType,
  diffProjection,
  EmitArgs,
  EmitValue,
  FunctionComponent,
  input,
  InputCell,
  Inputs,
  into,
  isChannelClientMessage,
  isChannelHostMessage,
  isClassComponent,
  isOutputTarget,
  output,
  OutputCell,
  OutputTarget,
  Patch,
  PatchPath,
  ReadableCell,
  viewKeys
};
// ==== index.d.ts ====
import {
  applyPatch,
  applyPatches,
  channel,
  ChannelClientMessage,
  ChannelHostMessage,
  ChannelPort,
  ChannelReplica,
  ChannelToken,
  ClassComponent,
  Command,
  CommandMap,
  Component,
  ComponentArgs,
  ComponentContext,
  ComponentProps,
  ComponentType,
  diffProjection,
  EmitArgs,
  EmitValue,
  FunctionComponent,
  input,
  InputCell,
  Inputs,
  into,
  isChannelClientMessage,
  isChannelHostMessage,
  isClassComponent,
  isOutputTarget,
  output,
  OutputCell,
  OutputTarget,
  Patch,
  PatchPath,
  ReadableCell,
  viewKeys
} from "./FunctionComponent-CEoy33Hr.js";
import {
  BehaviorSubject,
  Observable,
  Subscription
} from "rxjs";
import {
  AnimatedCell,
  AnimationDriver,
  CanvasHost,
  ComponentLikeElement,
  ComponentResolver,
  EditingState,
  EditingState as EditingState$1,
  IconRasterizer,
  ImageResolver,
  LayoutExplanation,
  LayoutInspector,
  MotionStateInput,
  MotionTiming,
  RendererBackend,
  TextMeasurer,
  UI_ROLES,
  UI_SEMANTIC_STATES,
  UiAnimation,
  UiChild,
  UiDurationToken,
  UiEasing,
  UiEasingToken,
  UiEditingController,
  UiElement,
  UiFindController,
  UiFocusManager,
  UiFrameClockFactory,
  UiInputDispatcher,
  UiKeyboardController,
  UiKeyModifiers,
  UiLength,
  UiMotion,
  UiNode,
  UiPlatformAdapter,
  UiPointerController,
  UiPointerDevice,
  UiReducedMotionPolicy,
  UiRole,
  UiScrollability,
  UiSelectionController,
  UiSemanticsAction,
  UiSemanticsMap,
  UiSemanticsMap as UiSemanticsMap$1,
  UiSemanticsPatch,
  UiSemanticsRecord,
  UiSemanticsRecord as UiSemanticsRecord$1,
  UiSemanticState,
  UiSemanticsUpdate,
  UiSpringSpec,
  UiSpringToken,
  UiTouchScroller,
  UiWheelController,
  VideoResolver
} from "@gesso/core";
declare class InternalState<T> extends BehaviorSubject<T> {
  label: string | undefined;
  constructor(initialValue: T);
  get value(): T;
  set value(next: T);
}
declare function internalState<T>(initialValue: T, label?: string): InternalState<T>;
declare class ServiceRegistry {
  private readonly services;
  register<T extends object>(ServiceClass: new () => T): T;
  adopt(ServiceClass: new () => object): boolean;
  get<T extends object>(ServiceClass: new () => T): T;
  has(ServiceClass: Function): boolean;
}
type Equality<T> = 'reference' | 'structural' | ((a: T, b: T) => boolean);
interface DeriveOptions<T> {
  readonly equal?: Equality<T>;
}
type Values<S extends readonly Observable<unknown>[]> = { [K in keyof S]: S[K] extends Observable<infer V> ? V : never; };
declare function derive<S extends readonly Observable<unknown>[], T>(sources: readonly [...S], project: (...values: Values<S>) => T, options?: DeriveOptions<T>): Observable<T>;
interface ComputedOptions<T> {
  readonly equal?: Equality<T>;
  readonly label?: string;
}
declare class ComputedCell<T> extends Observable<T> implements ReadableCell<T> {
  private readonly compute;
  label: string | undefined;
  private readonly equal;
  private readonly changes;
  private sources;
  private cached;
  private hasValue;
  private upstream;
  private subscribers;
  private attaching;
  private snapshotBy;
  private warnedStale;
  private staleWatch;
  constructor(compute: () => T, options?: ComputedOptions<T>);
  get value(): T;
  private watchForStaleRead;
  private warnStale;
  get observed(): boolean;
  private recompute;
  private attach;
  private detach;
  private onSourceChanged;
}
declare function computed<T>(compute: () => T, options?: ComputedOptions<T>): ComputedCell<T>;
declare function bind<T>(cell: InternalState<T>): {
  value: InternalState<T>;
  onChange: (next: T) => void;
};
declare function bind<T, V extends string, E extends string = 'onChange'>(cell: InternalState<T>, value: V, onChange?: E): { [K in V]: InternalState<T>; } & { [K in E]: (next: T) => void; };
interface ControlledValue<T> {
  readonly value: Observable<T>;
  current(): T;
  change(next: T): void;
}
interface ControlledOptions<T> {
  readonly component: string;
  readonly name: string;
  readonly source: InputCell<T | undefined>;
  readonly initial: InputCell<T | undefined>;
  readonly fallback: T;
  readonly onChange: OutputCell<[next: T]>;
}
declare function controlled<T>(options: ControlledOptions<T>): ControlledValue<T>;
declare function Define(tag: string): ClassDecorator;
declare function Input(): PropertyDecorator;
declare function Output(): PropertyDecorator;
declare function Inject<T extends Function>(StoreClass: T): PropertyDecorator;
declare function Channel(token: {
  name: string;
}): PropertyDecorator;
interface ChannelSource<View extends object, Commands extends object> {
  view: { readonly [K in keyof View]: Observable<View[K]>; };
  commands?: Commands;
}
declare function provide<View extends object, Commands extends object>(token: ChannelToken<View, Commands>, source: ChannelSource<View, Commands>, port: ChannelPort): ProvidedChannel;
declare class ProvidedChannel {
  private readonly token;
  private readonly source;
  private readonly port;
  private readonly subscriptions;
  private readonly previous;
  private readonly checked;
  private synced;
  constructor(token: ChannelToken<object, CommandMap>, source: ChannelSource<object, CommandMap>, port: ChannelPort);
  private receive;
  private runCommand;
  private sync;
  private publish;
  private resend;
  private post;
  dispose(): void;
}
declare class ChannelRegistry {
  private readonly replicas;
  attach<View extends object, Commands extends object>(token: ChannelToken<View, Commands>, port: ChannelPort): ChannelReplica<View, Commands>;
  get<View extends object, Commands extends object>(token: ChannelToken<View, Commands>): ChannelReplica<View, Commands>;
  has(token: ChannelToken<object, CommandMap>): boolean;
  all(): ChannelReplica<object, CommandMap>[];
  dispose(): void;
}
declare function findUnplainPath(value: unknown, path?: readonly (string | number)[]): string | null;
declare function requirePlainData(channelName: string, key: string, value: unknown): void;
interface MessageEndpoint {
  postMessage(message: unknown): void;
  onmessage: ((event: {
    data: unknown;
  }) => void) | null;
}
interface PortHandshake {
  type: 'gesso:port';
  key: string;
}
declare function isPortHandshake(value: unknown): value is PortHandshake;
interface WorkerHandle {
  open(key: string): MessagePort;
  readonly spawned: boolean;
  terminate(): void;
}
declare const APPLICATION_WORKER: WorkerHandle;
interface TransferTarget {
  postMessage(message: unknown, transfer: Transferable[]): void;
}
declare function portHandle(endpoint: TransferTarget): WorkerHandle;
declare function workerHandle(factory: () => Worker): WorkerHandle;
interface PortHost {
  onmessage: ((event: {
    data: unknown;
    ports?: readonly MessagePort[];
  }) => void) | null;
}
interface PortErrorMessage {
  type: 'port:error';
  message: string;
}
declare function isPortErrorMessage(value: unknown): value is PortErrorMessage;
declare function servePorts(onPort: (key: string, port: MessagePort) => boolean, names: () => readonly string[], host?: PortHost): () => void;
interface ChannelRegistration {
  token: {
    name: string;
    initial: object;
  };
  worker?: WorkerHandle | (() => Worker);
  source?: {
    view: Record<string, Observable<unknown>>;
    commands?: Record<string, Command>;
  };
}
interface ChannelRegistryHandle {
  registry: ChannelRegistry;
  dispose(): void;
}
declare function createChannelRegistry(registrations: readonly ChannelRegistration[], onError?: (channelName: string, message: string, stack?: string) => void): ChannelRegistryHandle;
interface ServedChannel {
  token: {
    name: string;
    initial: object;
  };
  source: {
    view: Record<string, Observable<unknown>>;
    commands?: Record<string, Command>;
  };
}
declare function serveChannels(channels: readonly ServedChannel[], host?: PortHost): () => void;
declare function pick<T, K extends keyof T>(source: Observable<T>, key: K): Observable<T[K]>;
declare function pickKeys<T extends object, K extends keyof T>(source: Observable<T>, keys: readonly K[]): { readonly [P in K]: Observable<T[P]>; };
declare function structurallyEqual<T>(a: T, b: T): boolean;
interface ComponentElement<P = Record<string, unknown>> {
  readonly kind: 'component';
  readonly tag: string;
  readonly component: ComponentType;
  readonly props: P;
  readonly key?: string | number;
}
declare function isComponentElement(value: unknown): value is ComponentElement;
type FrameworkChild = UiChild | ComponentElement;
declare function createComponent<C extends ComponentType>(component: C, ...args: ComponentArgs<C>): ComponentElement<ComponentProps<C>>;
type OverlayPlacement = 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end' | 'right' | 'right-start' | 'right-end';
interface OverlayEntry {
  readonly id: string;
  readonly content: UiChild;
  readonly anchor?: UiNode | null;
  readonly placement?: OverlayPlacement;
  readonly offset?: number;
  readonly top?: number;
  readonly right?: number;
  readonly bottom?: number;
  readonly left?: number;
  readonly center?: 'x' | 'y' | 'both';
  readonly dismissOnOutsidePress?: boolean;
  readonly zIndex?: number;
  readonly environment?: UiNode | null;
  readonly onClose?: () => void;
}
declare class OverlayService {
  readonly entries: InternalState<readonly OverlayEntry[]>;
  open(entry: OverlayEntry): void;
  close(id: string): void;
  closeAll(): void;
  isOpen(id: string): boolean;
}
declare class OverlayLayer extends Component {
  overlays: OverlayService;
  render(): UiElement;
  private renderEntries;
}
declare class ComponentHost<P extends Record<string, unknown> = Record<string, unknown>> {
  private readonly services;
  private readonly channels;
  readonly instance: Component | undefined;
  readonly element: ComponentElement<P>;
  readonly subscriptions: Subscription;
  private mounted;
  private output;
  private readonly inputSources;
  private readonly inputSubscriptions;
  private readonly functionalCells;
  private readonly mountHooks;
  private readonly unmountHooks;
  private rendering;
  constructor(element: ComponentElement<P>, services?: ServiceRegistry, channels?: ChannelRegistry);
  get component(): ComponentType;
  render(): UiChild;
  mount(): void;
  dispose(): void;
  updateProps(props: P): void;
  private renderFunction;
  private createInputRecord;
  private createContext;
  private wireInputs;
  private applyInput;
  private validateInputs;
  private wireChannels;
  private wireInjects;
}
declare class ComponentHostResolver implements ComponentResolver {
  private readonly services;
  private readonly channels;
  private readonly hosts;
  private pendingMounts;
  constructor(services?: ServiceRegistry, channels?: ChannelRegistry);
  resolve(element: ComponentLikeElement, anchorId: string): UiChild;
  release(anchorId: string): void;
  flushMounts(): void;
  dispose(): void;
  get size(): number;
  hostFor(anchorId: string): ComponentHost | undefined;
}
type ColorScheme = 'light' | 'dark';
type ColorSchemePreference = ColorScheme | 'auto';
declare function observeColorScheme(onChange: (scheme: ColorScheme) => void): () => void;
type PatternSegment = {
  readonly kind: 'static';
  readonly text: string;
} | {
  readonly kind: 'param';
  readonly name: string;
} | {
  readonly kind: 'rest';
};
type RouteParams<Path extends string> = Prettify<ParamsOf<Path>>;
type ParamsOf<Path extends string> = Path extends `${infer Head}/${infer Rest}` ? ParamOfSegment<Head> & ParamsOf<Rest> : ParamOfSegment<Path>;
type ParamOfSegment<Segment extends string> = Segment extends `:${infer Name}` ? { [K in Name]: string; } : Segment extends '*' ? {
  rest: string;
} : {};
type Prettify<T> = { [K in keyof T]: T[K]; } & {};
type HasNoParams<Path extends string> = keyof ParamsOf<Path> extends never ? true : false;
declare function buildPath(pattern: string, params?: Readonly<Record<string, string>>): string;
interface ParsedUrl {
  readonly path: string;
  readonly query: Readonly<Record<string, string>>;
}
declare function parseUrl(url: string): ParsedUrl;
declare function formatUrl(path: string, query?: Readonly<Record<string, string>>): string;
interface OutletProps {
  readonly outlet: UiChild;
}
interface RouteTarget {
  readonly route: RouteDefinition;
  readonly params: Readonly<Record<string, string>>;
  readonly query: Readonly<Record<string, string>>;
}
interface RouteContext<Path extends string = string> {
  readonly params: RouteParams<Path>;
  readonly query: Readonly<Record<string, string>>;
  readonly url: string;
}
type RouteGuard<Path extends string = string> = (context: RouteContext<Path>) => boolean | RouteTarget;
interface RouteDefinition<Path extends string = string> {
  readonly path: Path;
  readonly component: ComponentType;
  readonly parent?: RouteDefinition;
  readonly guard?: RouteGuard<Path>;
  readonly segments: readonly PatternSegment[];
  readonly chain: readonly RouteDefinition[];
}
interface RouteOptions<Path extends string> {
  readonly path: Path;
  readonly component: ComponentType;
  readonly parent?: RouteDefinition;
  readonly guard?: RouteGuard<Path>;
}
declare function route<const Path extends string>(options: RouteOptions<Path>): RouteDefinition<Path>;
declare function to<Path extends string>(route: RouteDefinition<Path>, ...args: ToArgs<Path>): RouteTarget;
interface ToOptions {
  readonly query?: Readonly<Record<string, string>>;
}
type ToArgs<Path extends string> = HasNoParams<Path> extends true ? [] : [params: RouteParams<Path>, options?: ToOptions];
interface RouteMatch {
  readonly route: RouteDefinition;
  readonly chain: readonly RouteDefinition[];
  readonly params: Readonly<Record<string, string>>;
  readonly query: Readonly<Record<string, string>>;
  readonly path: string;
  readonly url: string;
}
interface RouterHistorySink {
  push(url: string): void;
  replace(url: string): void;
  back(): void;
  forward(): void;
}
interface RouterRoutes {
  readonly routes: readonly RouteDefinition[];
  readonly notFound?: RouteDefinition;
}
interface NavigateOptions {
  readonly query?: Readonly<Record<string, string>>;
  readonly replace?: boolean;
}
type GoArgs<Path extends string> = HasNoParams<Path> extends true ? [options?: NavigateOptions] : [params: RouteParams<Path>, options?: NavigateOptions];
declare class RouterService {
  readonly url: InternalState<string>;
  readonly match: InternalState<RouteMatch | null>;
  private routes;
  private notFound;
  private history;
  setHistory(history: RouterHistorySink | null): void;
  setRoutes(routes: RouterRoutes): void;
  get declaredRoutes(): readonly RouteDefinition[];
  go<Path extends string>(route: RouteDefinition<Path>, ...args: GoArgs<Path>): void;
  navigate(url: string, options?: {
    replace?: boolean;
  }): void;
  back(): void;
  forward(): void;
  applyUrl(url: string): void;
  params<Path extends string>(route: RouteDefinition<Path>): RouteParams<Path> | null;
  observeParams<Path extends string>(route: RouteDefinition<Path>): Observable<RouteParams<Path> | null>;
  isActive(route: RouteDefinition): Observable<boolean>;
  private resolveInto;
  private publish;
  private resolve;
  private runGuards;
}
type ShellHistoryMode = 'path' | 'hash' | 'memory';
interface ShellHistoryOptions {
  readonly mode?: ShellHistoryMode;
  readonly base?: string;
  readonly initialUrl?: string;
}
interface ShellHistory {
  readonly url: string;
  push(url: string): void;
  replace(url: string): void;
  back(): void;
  forward(): void;
  onChange(listener: (url: string) => void): void;
  dispose(): void;
}
interface HistoryWindow {
  readonly location: {
    pathname: string;
    search: string;
    hash: string;
  };
  readonly history: {
    pushState(data: unknown, title: string, url: string): void;
    replaceState(data: unknown, title: string, url: string): void;
    back(): void;
    forward(): void;
  };
  addEventListener(type: string, listener: () => void): void;
  removeEventListener(type: string, listener: () => void): void;
}
declare function createShellHistory(options?: ShellHistoryOptions, host?: HistoryWindow | undefined): ShellHistory;
interface UiNodeReport {
  readonly id: string;
  readonly type: string;
  readonly box: {
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
  };
  readonly owners: readonly UiOwnerReport[];
  readonly props: readonly UiPropReport[];
  readonly environment: readonly UiEnvironmentReport[];
  readonly modifiers: readonly string[];
  readonly listens: readonly string[];
  readonly beneath: readonly UiBeneathReport[];
  readonly semantics?: UiSemanticsReport;
  readonly explanation: string;
}
interface UiBeneathReport {
  readonly id: string;
  readonly type: string;
  readonly owner?: string;
  readonly listens: readonly string[];
}
interface UiOwnerReport {
  readonly name: string;
  readonly anchorId: string;
}
type UiPropOrigin = 'element' | 'binding' | 'modifier';
interface UiPropReport {
  readonly name: string;
  readonly value: string;
  readonly origin: UiPropOrigin;
  readonly source?: string;
}
interface UiEnvironmentReport {
  readonly key: string;
  readonly value: string;
  readonly provided: boolean;
}
interface UiSemanticsReport {
  readonly role?: string;
  readonly label?: string;
  readonly value?: string;
  readonly states?: readonly string[];
}
declare function printPropValue(value: unknown): string;
declare function formatNodeReport(report: UiNodeReport): string;
type ShellRequest = {
  type: 'clipboard';
  text: string;
} | {
  type: 'openUrl';
  url: string;
} | {
  type: 'history';
  action: 'push' | 'replace';
  url: string;
} | {
  type: 'history';
  action: 'back' | 'forward';
  url?: undefined;
};
declare class ShellService {
  private handler;
  private readonly scheme;
  readonly colorScheme: ReadableCell<ColorScheme>;
  get currentColorScheme(): ColorScheme;
  setHandler(handler: ((request: ShellRequest) => void) | null): void;
  applyColorScheme(scheme: ColorScheme): void;
  copyText(text: string): void;
  openUrl(url: string): void;
}
type UiDuration = UiDurationToken | number;
type UiEasingChoice = UiEasingToken | UiEasing;
interface AnimateOptions {
  duration?: UiDuration;
  easing?: UiEasingChoice;
  stepMs?: number;
  repeat?: boolean;
  reducedMotion?: UiReducedMotionPolicy;
  delay?: number;
}
interface SpringOptions {
  spring?: UiSpringToken | UiSpringSpec;
  stiffness?: number;
  damping?: number;
  mass?: number;
  velocity?: number;
  restDelta?: number;
  reducedMotion?: UiReducedMotionPolicy;
  delay?: number;
}
declare class AnimationService {
  readonly reducedMotion: InternalState<boolean>;
  private driver;
  private motionVocabulary;
  setDriver(driver: AnimationDriver | null): void;
  setMotion(motion: UiMotion): void;
  get motion(): UiMotion;
  applyReducedMotion(reduced: boolean): void;
  animate<T>(cell: AnimatedCell<T>, to: T, options?: AnimateOptions): Observable<T>;
  spring(cell: AnimatedCell<number>, to: number, options?: SpringOptions): Observable<number>;
  stop<T>(cell: AnimatedCell<T>): boolean;
  animationFor<T>(cell: AnimatedCell<T>): UiAnimation<T> | undefined;
  private resolveDuration;
  private resolveEasing;
}
interface AudioSample {
  readonly status: AudioStatus;
  readonly position: number;
  readonly duration: number;
  readonly buffered: number;
  readonly at: number;
  readonly error?: string;
}
type AudioStatus = 'idle' | 'loading' | 'playing' | 'paused' | 'ended' | 'error';
type AudioRequest = {
  readonly type: 'load';
  readonly src: string;
  readonly autoplay: boolean;
} | {
  readonly type: 'play';
} | {
  readonly type: 'pause';
} | {
  readonly type: 'seek';
  readonly seconds: number;
} | {
  readonly type: 'volume';
  readonly level: number;
} | {
  readonly type: 'metadata';
  readonly metadata: AudioMetadata | null;
};
type AudioAction = 'play' | 'pause' | 'next' | 'previous';
interface AudioMetadata {
  readonly title: string;
  readonly artist: string;
  readonly album?: string;
  readonly artwork?: string;
}
interface AudioState {
  readonly status: AudioStatus;
  readonly position: number;
  readonly duration: number;
  readonly buffered: number;
  readonly src: string | null;
  readonly error?: string;
}
declare class AudioService {
  private handler;
  private animations;
  private readonly sample;
  private readonly source;
  private readonly position;
  private readonly actionSubject;
  readonly state: Observable<AudioState>;
  readonly actions: Observable<AudioAction>;
  get current(): AudioState;
  setHandler(handler: ((request: AudioRequest) => void) | null): void;
  setAnimations(animations: AnimationService | null): void;
  applySample(sample: AudioSample): void;
  applyAction(action: AudioAction): void;
  load(src: string, options?: {
    readonly autoplay?: boolean;
  }): void;
  play(): void;
  pause(): void;
  seek(seconds: number): void;
  setVolume(level: number): void;
  setMetadata(metadata: AudioMetadata | null): void;
}
interface MediaOptions {
  resolver?: ImageResolver;
  rasterizer?: IconRasterizer;
  videoResolver?: VideoResolver;
}
declare class MediaService {
  private imageResolver;
  private iconRasterizer;
  private videoResolver;
  private ownsResolver;
  private ownsRasterizer;
  private ownsVideoResolver;
  get images(): ImageResolver;
  get icons(): IconRasterizer;
  get videos(): VideoResolver;
  setResolver(resolver: ImageResolver): void;
  setVideoResolver(resolver: VideoResolver): void;
  setRasterizer(rasterizer: IconRasterizer): void;
  dispose(): void;
}
interface FontFaceDeclaration {
  source: string | ArrayBuffer;
  weight?: string | number;
  style?: 'normal' | 'italic' | 'oblique';
  stretch?: string;
  unicodeRange?: string;
  display?: 'auto' | 'block' | 'swap' | 'fallback' | 'optional';
}
interface FontFamilyDeclaration {
  family: string;
  faces: readonly FontFaceDeclaration[];
  fallback?: readonly string[];
}
type FontFamilyStatus = 'undeclared' | 'unavailable' | 'loading' | 'loaded' | 'error';
interface FontFaceLike {
  readonly family: string;
  load(): Promise<unknown>;
}
interface FontHost {
  readonly fonts: {
    add(face: FontFaceLike): unknown;
  } | undefined;
  createFace(family: string, source: string | ArrayBuffer, descriptors: FontFaceDescriptors): FontFaceLike;
}
declare class FontService {
  private readonly statuses;
  private readonly pending;
  private readonly failed;
  private readonly batches;
  private listener;
  private disposed;
  declare(families: readonly FontFamilyDeclaration[], host?: FontHost): void;
  get ready(): Promise<void>;
  statusOf(family: string): FontFamilyStatus;
  get families(): readonly string[];
  setListener(listener: ((family: string) => void) | null): void;
  dispose(): void;
  private loadFace;
  private settle;
}
declare const UI_FRAME_PHASES: readonly ['ticks', 'patches', 'environment', 'virtualize', 'layout', 'semantics', 'render'];
type UiFramePhase = (typeof UI_FRAME_PHASES)[number];
type FramePhaseTimings = Record<UiFramePhase, number>;
interface RuntimeInput {
  readonly dispatcher: UiInputDispatcher;
  readonly pointer: UiPointerController;
  readonly wheel: UiWheelController;
  readonly keyboard: UiKeyboardController;
  readonly focus: UiFocusManager;
  readonly editing: UiEditingController;
  readonly selection: UiSelectionController;
  readonly find: UiFindController;
  readonly touchScroll: UiTouchScroller;
}
type RendererChoice = RendererBackend | 'auto';
interface GessoRuntimeOptions {
  root: FrameworkChild;
  canvas: CanvasHost;
  renderer?: RendererChoice;
  measureCanvas?: CanvasHost;
  textMeasurer?: TextMeasurer;
  media?: MediaOptions;
  fonts?: readonly FontFamilyDeclaration[];
  services?: ServiceRegistry;
  routes?: RouterRoutes;
  channels?: ChannelRegistry;
  clock?: UiFrameClockFactory;
  width?: number;
  height?: number;
  dpr?: number;
}
declare class GessoRuntime {
  readonly services: ServiceRegistry;
  readonly channels: ChannelRegistry;
  readonly input: RuntimeInput;
  readonly inspector: LayoutInspector;
  private readonly resolver;
  private readonly graph;
  private readonly engine;
  private readonly builder;
  private readonly scheduler;
  private readonly inputLatency;
  private readonly canvas;
  private readonly textMeasurer;
  private canvasSurface;
  private renderer;
  private rendererState;
  readonly rendererReady: Promise<RendererBackend>;
  private readonly dispatcher;
  private width;
  private height;
  private root;
  private appRoot;
  private constraints;
  private pixelRatio;
  private lastFrameMs;
  private frameListener;
  private rendererErrorListener;
  private gpuTimings;
  private inspectListener;
  private lastInspection;
  private cursorListener;
  private lastCursor;
  private scrollabilityListener;
  private lastScrollability;
  private lastScrollsAnything;
  private editingListener;
  private selectionController;
  private findController;
  private readonly focusManager;
  private hitTester;
  private readonly layoutNotifier;
  private readonly smoothScroller;
  private visible;
  private readonly animations;
  private readonly sharedElements;
  private readonly focusNotifier;
  private readonly environmentNotifier;
  private semantics;
  private semanticsListener;
  private semanticsBoxes;
  private lastFocusedId;
  private semanticsStale;
  private lastEditingState;
  private shellListener;
  private audioListener;
  private caretTimer;
  private scrollbarTimer;
  private inspectorTimer;
  private animationTimer;
  private replicas;
  private phaseTimings;
  private started;
  constructor(options: GessoRuntimeOptions);
  deferPatchesFrom(sources: readonly PatchSource[]): void;
  start(): void;
  get rendererBackend(): RendererBackend | 'pending';
  onRendererError(listener: ((message: string) => void) | null): void;
  onListenerError(listener: ((message: string, stack?: string) => void) | null): void;
  private reportRendererError;
  private fallBackToCanvas2D;
  private requestRepaint;
  private fontsChanged;
  resize(width: number, height: number, dpr?: number): void;
  onFrame(listener: ((metrics: FrameMetrics) => void) | null): void;
  noteInput(at: number | undefined): void;
  setInspectorEnabled(enabled: boolean): void;
  onInspect(listener: ((report: UiNodeReport | null) => void) | null): void;
  onCursor(listener: ((cursor: string | null) => void) | null): void;
  get cursor(): string | null;
  onScrollability(listener: ((scrollability: UiScrollability, scrollsAnything: boolean) => void) | null): void;
  get scrollability(): UiScrollability;
  onEditingState(listener: ((state: EditingState$1 | null) => void) | null): void;
  get editingState(): EditingState$1 | null;
  onShellRequest(listener: ((request: ShellRequest) => void) | null): void;
  onAudioRequest(listener: ((request: AudioRequest) => void) | null): void;
  applyAudioSample(sample: AudioSample): void;
  applyAudioAction(action: AudioAction): void;
  setTextInputSource(source: 'proxy' | 'keys'): void;
  setVisible(visible: boolean): void;
  setReducedMotion(reduced: boolean): void;
  setUrl(url: string): void;
  setColorScheme(scheme: ColorScheme): void;
  get reducedMotion(): boolean;
  get colorScheme(): ColorScheme;
  get sharedElementNames(): readonly string[];
  explain(node: UiNode): LayoutExplanation;
  inspectNode(node: UiNode): UiNodeReport;
  private beneathAtPointer;
  private ownersOf;
  private propsOf;
  private environmentOf;
  private semanticsOf;
  debugRoot(): UiNode;
  debugLayoutBox(node: UiNode): {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  layoutRoot(): UiNode;
  scrollIntoView(node: UiNode, padding?: number): void;
  reload(rootDefinition: FrameworkChild, services?: readonly (new () => object)[]): void;
  dispose(): void;
  private buildRoot;
  private resolveRootElement;
  private createInput;
  onSemantics(listener: ((update: UiSemanticsUpdate) => void) | null): void;
  semanticsTree(): UiSemanticsMap$1;
  applySemanticsAction(action: UiSemanticsAction): void;
  private updateSemantics;
  private collectSemanticsBoxes;
  private revealBox;
  private handleHoverChange;
  private createScrollSink;
  private runPreCollectPhases;
  private hasVirtualWindows;
  private updateVirtualWindows;
  private collectVirtualMeasures;
  private extentOf;
  private handleFrame;
  private scheduleAnimationTick;
  private scheduleScrollbarFade;
  private scheduleCaretBlink;
  private sendEditingState;
  private scheduleInspectorRepaint;
  private sendCursor;
  private sendScrollability;
  private sendInspection;
  private hoveredReport;
  private timePhase;
  get lastFrameDurationMs(): number;
}
interface PatchSource {
  readonly hasPendingPatches: boolean;
  flush(): void;
  deferPatches(scheduleFlush: () => void): void;
}
interface FrameMetrics {
  frame: number;
  durationMs: number;
  nodes: number;
  measured: number;
  relayoutRoots: number;
  phases: FramePhaseTimings;
  renderer: RendererBackend | 'pending';
  gpu: GpuStageTimings | null;
  at: number;
  inputLatencyMs: number | null;
}
interface GpuStageTimings {
  prepare: number;
  upload: number;
  encode: number;
}
declare class GessoAppBuilder {
  private root;
  private readonly channelRegistrations;
  private readonly serviceRegistrations;
  private frameListener;
  private inspectListener;
  private errorListener;
  private rendererChoice;
  private routes;
  private historyOptions;
  private mediaOptions;
  private fontDeclarations;
  private app;
  private colorSchemePreference;
  constructor(root: FrameworkChild | ComponentType);
  useChannel<V extends object, C extends object>(token: ChannelToken<V, C>, options: {
    worker?: WorkerHandle | (() => Worker);
    source?: ChannelSource<V, C>;
  }): this;
  useService(ServiceClass: new () => object): this;
  useRoutes(routes: RouterRoutes): this;
  useMedia(media: MediaOptions): this;
  useFonts(families: readonly FontFamilyDeclaration[]): this;
  useHistory(history: ShellHistoryOptions): this;
  renderer(choice: RendererChoice): this;
  onFrame(listener: (metrics: FrameMetrics) => void): this;
  onInspect(listener: (report: UiNodeReport | null) => void): this;
  onError(listener: (message: string, stack: string | undefined, source: 'renderer' | 'listener') => void): this;
  setInspector(enabled: boolean): void;
  reload(root: FrameworkChild | ComponentType, services?: readonly (new () => object)[]): this;
  setColorScheme(preference: ColorSchemePreference): this;
  mountSync(host: HTMLElement | string): () => void;
}
type ShellToRuntimeMessage = {
  type: 'init';
  canvas: OffscreenCanvas;
  width: number;
  height: number;
  dpr: number;
  renderer?: RendererChoice;
  textInput?: 'proxy' | 'keys';
  appPort?: MessagePort;
  accessibility?: boolean;
} | {
  type: 'resize';
  width: number;
  height: number;
  dpr: number;
} |
{
  type: 'pointerDown';
  x: number;
  y: number;
  buttons: number;
  modifiers: UiKeyModifiers;
  pointer?: UiPointerDevice;
  at?: number;
} | {
  type: 'pointerMove';
  x: number;
  y: number;
  buttons: number;
  modifiers: UiKeyModifiers;
  pointer?: UiPointerDevice;
  at?: number;
} | {
  type: 'pointerUp';
  x: number;
  y: number;
  buttons: number;
  modifiers: UiKeyModifiers;
  pointer?: UiPointerDevice;
  at?: number;
} | {
  type: 'pointerCancel';
  pointer?: UiPointerDevice;
  at?: number;
} |
{
  type: 'wheel';
  x: number;
  y: number;
  deltaX: number;
  deltaY: number;
  modifiers: UiKeyModifiers;
  deltaMode?: number;
  wheelDeltaY?: number;
  at?: number;
} | {
  type: 'keyDown';
  key: string;
  modifiers: UiKeyModifiers;
  at?: number;
} | {
  type: 'keyUp';
  key: string;
  modifiers: UiKeyModifiers;
  at?: number;
} |
{
  type: 'beforeInput';
  inputType: string;
  data: string | null;
  at?: number;
} | {
  type: 'compositionStart';
  at?: number;
} |
{
  type: 'compositionUpdate';
  text: string;
  caret: number;
  at?: number;
} |
{
  type: 'compositionEnd';
  text: string;
  at?: number;
} | {
  type: 'paste';
  text: string;
  at?: number;
} |
{
  type: 'blur';
} |
{
  type: 'visibility';
  visible: boolean;
} |
{
  type: 'reducedMotion';
  reduced: boolean;
} |
{
  type: 'colorScheme';
  scheme: ColorScheme;
} |
{
  type: 'url';
  url: string;
} | {
  type: 'inspector';
  enabled: boolean;
} |
{
  type: 'semanticsAction';
  action: UiSemanticsAction;
} |
{
  type: 'audioSample';
  sample: AudioSample;
} |
{
  type: 'audioAction';
  action: AudioAction;
} |
{
  type: 'tick';
  time: number;
} | {
  type: 'dispose';
};
type RuntimeErrorSource = 'message' | 'uncaught' | 'renderer' | 'channel' | 'listener';
type RuntimeToShellMessage = {
  type: 'ready';
} | {
  type: 'frame';
  frame: number;
  durationMs: number;
  nodes: number;
  measured: number;
  relayoutRoots: number;
  at: number;
  inputLatencyMs: number | null;
  phases: FramePhaseTimings;
  renderer: RendererBackend | 'pending';
  gpu: GpuStageTimings | null;
} | {
  type: 'error';
  message: string;
  stack?: string;
  source: RuntimeErrorSource;
} |
{
  type: 'inspect';
  report: UiNodeReport | null;
} |
{
  type: 'cursor';
  cursor: string | null;
} |
{
  type: 'scrollability';
  scrollability: UiScrollability;
  scrollsAnything: boolean;
} |
{
  type: 'editing';
  state: EditingState$1 | null;
} |
{
  type: 'clipboard';
  text: string;
} |
{
  type: 'openUrl';
  url: string;
} |
{
  type: 'history';
  action: 'push' | 'replace' | 'back' | 'forward';
  url?: string;
} |
{
  type: 'audio';
  request: AudioRequest;
} |
{
  type: 'frameLoop';
  running: boolean;
} | {
  type: 'semantics';
  update: UiSemanticsUpdate;
};
interface WorkerAppOptions {
  renderWorker: (() => Worker) | URL | string;
  renderer?: RendererChoice;
  onFrame?: (metrics: FrameMetrics) => void;
  appLogicWorker?: Worker | (() => Worker) | URL | string;
  onError?: (message: string, stack: string | undefined, source: RuntimeErrorSource) => void;
  onInspect?: (report: UiNodeReport | null) => void;
  interceptFind?: boolean;
  colorScheme?: ColorSchemePreference;
  accessibility?: boolean;
  history?: ShellHistoryOptions;
}
declare class WorkerApp {
  private readonly options;
  private renderWorker;
  private appLogicWorker;
  private ownsAppLogicWorker;
  private canvas;
  private host;
  private resizeObserver;
  private detachInput;
  private proxy;
  private mirror;
  private audio;
  private scrollability;
  private history;
  private ready;
  private frameHandle;
  private detachColorScheme;
  private colorSchemePreference;
  constructor(options: WorkerAppOptions);
  get appLogic(): WorkerHandle | undefined;
  mount(host: HTMLElement | string): () => void;
  private handleWorkerFailure;
  private report;
  private forwardKeyDown;
  private forwardKeyUp;
  setInspector(enabled: boolean): void;
  setColorScheme(preference: ColorSchemePreference): void;
  private setFrameLoop;
  dispose(): void;
  private readonly handleWorkerMessage;
  private attachHistory;
  private applyHistory;
  private post;
  private observeResize;
  private wouldConsumeWheel;
  private attachInput;
}
declare function createApp(options: WorkerAppOptions): WorkerApp;
declare function createApp(root: FrameworkChild | ComponentType): GessoAppBuilder;
interface GessoAppOptions {
  host: HTMLElement;
  root: FrameworkChild;
  services?: ServiceRegistry;
  channels?: ChannelRegistry;
  routes?: RouterRoutes;
  history?: ShellHistoryOptions;
  canvas?: CanvasHost;
  renderer?: RendererChoice;
  clock?: UiFrameClockFactory;
  input?: boolean;
  accessibility?: boolean;
  colorScheme?: ColorSchemePreference;
  media?: MediaOptions;
  fonts?: readonly FontFamilyDeclaration[];
}
declare class GessoApp {
  private readonly runtime;
  private readonly canvas;
  private readonly host;
  private readonly inputEnabled;
  private readonly accessibilityEnabled;
  private readonly adapter;
  private readonly historyOptions;
  private running;
  private resizeObserver;
  private proxy;
  private audio;
  private mirror;
  private history;
  private detachVisibility;
  private detachReducedMotion;
  private detachColorScheme;
  private colorSchemePreference;
  constructor(options: GessoAppOptions);
  get services(): ServiceRegistry;
  get input(): UiPlatformAdapter;
  mount(): void;
  deferPatchesFrom(sources: readonly PatchSource[]): void;
  onFrame(listener: ((metrics: FrameMetrics) => void) | null): void;
  get rendererReady(): Promise<'canvas2d' | 'webgpu'>;
  resize(width: number, height: number): void;
  reload(root: FrameworkChild, services?: readonly (new () => object)[]): void;
  setInspector(enabled: boolean): void;
  setColorScheme(preference: ColorSchemePreference): void;
  onInspect(listener: ((report: UiNodeReport | null) => void) | null): void;
  onError(listener: ((message: string, stack: string | undefined, source: 'renderer' | 'listener') => void) | null): void;
  debugRoot(): UiNode;
  dispose(): void;
  private attachInput;
  private attachSemanticsMirror;
  private attachHistory;
  private handleShellRequest;
  private observeResize;
}
declare class FrameService {
  private readonly subject;
  readonly frames: Observable<FrameMetrics>;
  publish(metrics: FrameMetrics): void;
}
interface AudioElementLike extends EventTarget {
  src: string;
  currentTime: number;
  volume: number;
  preload: string;
  readonly duration: number;
  readonly paused: boolean;
  readonly ended: boolean;
  readonly buffered: {
    readonly length: number;
    start(index: number): number;
    end(index: number): number;
  };
  readonly error: {
    readonly code: number;
    readonly message?: string;
  } | null;
  play(): Promise<void>;
  pause(): void;
  load(): void;
}
interface MediaSessionLike {
  metadata: unknown;
  playbackState: 'none' | 'paused' | 'playing';
  setActionHandler(action: string, handler: ((details: {
    seekTime?: number;
  }) => void) | null): void;
}
interface AudioSinkOutput {
  sample(sample: AudioSample): void;
  action(action: AudioAction): void;
}
interface AudioSinkOptions {
  readonly createElement?: () => AudioElementLike;
  readonly mediaSession?: MediaSessionLike | null;
  readonly sampleEveryMs?: number;
}
declare class AudioSink {
  private readonly out;
  private readonly element;
  private readonly session;
  private readonly sampleEveryMs;
  private timer;
  private waiting;
  private refused;
  private readonly onEvent;
  constructor(out: AudioSinkOutput, options?: AudioSinkOptions);
  handle(request: AudioRequest): void;
  dispose(): void;
  private play;
  private handleEvent;
  private status;
  private emit;
  private startTimer;
  private stopTimer;
  private setMetadata;
  private bindSession;
}
interface RouteTransition {
  enter?: MotionStateInput;
  exit?: MotionStateInput;
  mode?: 'together' | 'wait';
  timing?: MotionTiming;
}
declare class RouterOutlet extends Component {
  router: RouterService;
  transition: InputCell<RouteTransition | undefined>;
  render(): UiChild;
}
interface PresenceProps {
  children?: UiChild | readonly UiChild[];
  enter?: MotionStateInput;
  exit?: MotionStateInput;
  mode?: 'together' | 'wait';
  timing?: MotionTiming;
  width?: UiLength | number;
  height?: UiLength | number;
  exitTimeout?: number;
}
declare function Presence(props: Inputs<PresenceProps>, ctx: ComponentContext): UiChild;
declare function observeReducedMotion(onChange: (reduced: boolean) => void): () => void;
declare function observeMediaQuery(query: string, onChange: (matches: boolean) => void): () => void;
declare class FindService {
  readonly open: InternalState<boolean>;
  readonly query: InternalState<string>;
  readonly matchCount: InternalState<number>;
  readonly activeMatch: InternalState<number>;
  private controller;
  private detach;
  private field;
  setController(controller: UiFindController | null): void;
  setField(node: UiNode | null): void;
  openFind(): void;
  close(): void;
  search(query: string, matchCase?: boolean): void;
  next(): void;
  previous(): void;
  refresh(): void;
  private sync;
}
declare class FocusService {
  readonly focused: InternalState<UiNode | null>;
  readonly trapped: InternalState<boolean>;
  private manager;
  private detach;
  private queued;
  setManager(manager: UiFocusManager | null): void;
  focus(node: UiNode): void;
  blur(): void;
  focusNext(): void;
  focusPrevious(): void;
  trap(scope: UiNode): void;
  releaseTrap(): void;
  private run;
  private sync;
}
interface EditingProxySink {
  beforeInput(inputType: string, data: string | null): void;
  compositionStart(): void;
  compositionUpdate(text: string, caret: number): void;
  compositionEnd(text: string): void;
  paste(text: string): void;
  blur(): void;
  keyDown?(event: KeyboardEvent): void;
  keyUp?(event: KeyboardEvent): void;
}
declare class EditingProxy {
  private readonly canvas;
  private readonly sink;
  private readonly textarea;
  private readonly doc;
  private readonly view;
  private state;
  private composing;
  private disposed;
  private refocusing;
  private readonly detach;
  constructor(canvas: HTMLCanvasElement, sink: EditingProxySink);
  get active(): boolean;
  get element(): HTMLTextAreaElement;
  update(state: EditingState$1 | null): void;
  focus(): void;
  raiseKeyboard(): void;
  describe(record: UiSemanticsRecord$1 | null): void;
  dispose(): void;
  private position;
  private mirror;
  private listen;
}
declare function writeClipboard(text: string, doc?: Document): void;
interface SemanticsMirrorSink {
  action(action: UiSemanticsAction): void;
  keyDown?(event: KeyboardEvent): void;
  keyUp?(event: KeyboardEvent): void;
}
interface EditingMirrorTarget {
  readonly active: boolean;
  describe(record: UiSemanticsRecord$1 | null): void;
  focus(): void;
}
declare class SemanticsMirror {
  private readonly canvas;
  private readonly sink;
  private readonly editing;
  private readonly container;
  private readonly doc;
  private readonly entries;
  private readonly ids;
  private readonly detach;
  private resizeObserver;
  private stopTracking;
  private applying;
  private focusedId;
  private disposed;
  constructor(canvas: HTMLCanvasElement, sink: SemanticsMirrorSink, editing?: EditingMirrorTarget | null);
  get element(): HTMLElement;
  elementFor(id: string): HTMLElement | undefined;
  apply(update: UiSemanticsUpdate): void;
  dispose(): void;
  private upsert;
  private createElement;
  private describe;
  private place;
  private remove;
  private applyFocus;
  private listen;
  private idOf;
  private trackCanvas;
}
interface WorkerErrorEvent {
  message?: string;
  error?: unknown;
  filename?: string;
  lineno?: number;
  colno?: number;
}
interface WorkerRejectionEvent {
  reason?: unknown;
}
interface WorkerGlobal {
  onmessage: ((event: MessageEvent<ShellToRuntimeMessage>) => void) | null;
  postMessage(message: RuntimeToShellMessage): void;
  addEventListener(type: 'error', listener: (event: WorkerErrorEvent) => void): void;
  addEventListener(type: 'unhandledrejection', listener: (event: WorkerRejectionEvent) => void): void;
}
declare function renderRoot(root: FrameworkChild | ComponentType): RenderWorkerApp;
declare class RenderWorkerApp {
  private readonly channelRegistrations;
  private readonly serviceRegistrations;
  private routes;
  private media;
  private fonts;
  private root;
  private readonly host;
  private runtime;
  private clock;
  private channels;
  private appLogicWorker;
  constructor(root: FrameworkChild | ComponentType, host?: WorkerGlobal);
  private reportUncaught;
  reload(root: FrameworkChild | ComponentType, services?: readonly (new () => object)[]): void;
  useChannel<V extends object, C extends object>(token: ChannelToken<V, C>, options?: {
    worker?: WorkerHandle | (() => Worker);
    source?: ChannelSource<V, C>;
  }): this;
  useService(ServiceClass: new () => object): this;
  useRoutes(routes: RouterRoutes): this;
  useMedia(media: MediaOptions): this;
  useFonts(families: readonly FontFamilyDeclaration[]): this;
  receive(message: ShellToRuntimeMessage): void;
  private dispatch;
  private resolveWorker;
  private initialize;
}
export {
  AnimationService,
  APPLICATION_WORKER,
  applyPatch,
  applyPatches,
  AudioService,
  AudioSink,
  bind,
  buildPath,
  channel,
  Channel,
  ChannelRegistry,
  ChannelReplica,
  Component,
  ComponentHost,
  ComponentHostResolver,
  computed,
  ComputedCell,
  controlled,
  createApp,
  createChannelRegistry,
  createComponent,
  createShellHistory,
  Define,
  derive,
  diffProjection,
  EditingProxy,
  FindService,
  findUnplainPath,
  FocusService,
  FontService,
  formatNodeReport,
  formatUrl,
  FrameService,
  GessoApp,
  GessoAppBuilder,
  GessoRuntime,
  Inject,
  input,
  Input,
  InputCell,
  internalState,
  InternalState,
  into,
  isChannelClientMessage,
  isChannelHostMessage,
  isClassComponent,
  isComponentElement,
  isOutputTarget,
  isPortErrorMessage,
  isPortHandshake,
  MediaService,
  observeColorScheme,
  observeMediaQuery,
  observeReducedMotion,
  output,
  Output,
  OverlayLayer,
  OverlayService,
  parseUrl,
  pick,
  pickKeys,
  portHandle,
  Presence,
  printPropValue,
  provide,
  ProvidedChannel,
  renderRoot,
  RenderWorkerApp,
  requirePlainData,
  route,
  RouterOutlet,
  RouterService,
  SemanticsMirror,
  serveChannels,
  servePorts,
  ServiceRegistry,
  ShellService,
  structurallyEqual,
  to,
  type AnimateOptions,
  type AudioAction,
  type AudioElementLike,
  type AudioMetadata,
  type AudioRequest,
  type AudioSample,
  type AudioSinkOptions,
  type AudioSinkOutput,
  type AudioState,
  type AudioStatus,
  type ChannelClientMessage,
  type ChannelHostMessage,
  type ChannelPort,
  type ChannelRegistration,
  type ChannelRegistryHandle,
  type ChannelSource,
  type ChannelToken,
  type ClassComponent,
  type ColorScheme,
  type ColorSchemePreference,
  type Command,
  type CommandMap,
  type ComponentContext,
  type ComponentElement,
  type ComponentProps,
  type ComponentType,
  type ComputedOptions,
  type ControlledOptions,
  type ControlledValue,
  type DeriveOptions,
  type EditingMirrorTarget,
  type EditingProxySink,
  type EditingState,
  type EmitArgs,
  type EmitValue,
  type Equality,
  type FontFaceDeclaration,
  type FontFaceLike,
  type FontFamilyDeclaration,
  type FontFamilyStatus,
  type FontHost,
  type FrameMetrics,
  type FramePhaseTimings,
  type FrameworkChild,
  type FunctionComponent,
  type GessoAppOptions,
  type GessoRuntimeOptions,
  type Inputs,
  type MediaOptions,
  type MediaSessionLike,
  type MessageEndpoint,
  type OutletProps,
  type OutputCell,
  type OutputTarget,
  type OverlayEntry,
  type OverlayPlacement,
  type Patch,
  type PatchPath,
  type PortHandshake,
  type PortHost,
  type PresenceProps,
  type ReadableCell,
  type RendererChoice,
  type RouteContext,
  type RouteDefinition,
  type RouteGuard,
  type RouteMatch,
  type RouteOptions,
  type RouteParams,
  type RouterHistorySink,
  type RouterRoutes,
  type RouteTarget,
  type RuntimeErrorSource,
  type RuntimeInput,
  type RuntimeToShellMessage,
  type SemanticsMirrorSink,
  type ServedChannel,
  type ShellHistory,
  type ShellHistoryMode,
  type ShellHistoryOptions,
  type ShellRequest,
  type ShellToRuntimeMessage,
  type SpringOptions,
  type UiDuration,
  type UiEasingChoice,
  type UiEnvironmentReport,
  type UiFramePhase,
  type UiNodeReport,
  type UiOwnerReport,
  type UiPropOrigin,
  type UiPropReport,
  type UiRole,
  type UiSemanticsMap,
  type UiSemanticsPatch,
  type UiSemanticsRecord,
  type UiSemanticsReport,
  type UiSemanticState,
  type WorkerAppOptions,
  type WorkerHandle,
  UI_FRAME_PHASES,
  UI_ROLES,
  UI_SEMANTIC_STATES,
  viewKeys,
  WorkerApp,
  workerHandle,
  writeClipboard
};
// ==== jsx/jsx-dev-runtime.d.ts ====
import {
  Fragment,
  jsx,
  JSX,
  jsxDEV,
  jsxs
} from "./jsx-runtime.js";
export {
  Fragment,
  jsx,
  jsxDEV,
  jsxs,
  type JSX
};
// ==== jsx/jsx-runtime.d.ts ====
import {
  ClassComponent,
  Component,
  ComponentContext,
  ComponentProps,
  ComponentType,
  InputCell
} from "../FunctionComponent-CEoy33Hr.js";
import {
  Observable
} from "rxjs";
import {
  BoxProps,
  ButtonProps,
  ColumnProps,
  ComponentLikeElement,
  EditableTextProps,
  GridProps,
  RowProps,
  ScrollViewProps,
  StackProps,
  TextProps,
  UiChild,
  UiElement,
  UiNodeType
} from "@gesso/core";
type JsxChild = UiChild | string | number | boolean | null | undefined;
type JsxChildren = JsxChild | readonly JsxChildren[];
type WithChildren<P, C = JsxChildren> = P & {
  children?: C;
};
type TextChildren = string | number | Observable<string | number>;
declare const INTRINSIC_TYPES: {
  readonly text: UiNodeType.Text;
  readonly editabletext: UiNodeType.EditableText;
  readonly button: UiNodeType.Button;
  readonly box: UiNodeType.Box;
  readonly stack: UiNodeType.Box;
  readonly row: UiNodeType.Row;
  readonly column: UiNodeType.Column;
  readonly scrollview: UiNodeType.ScrollView;
  readonly grid: UiNodeType.Grid;
};
type IntrinsicTag = keyof typeof INTRINSIC_TYPES;
declare namespace JSX {
  type Element = UiElement | ComponentLikeElement;
  type ElementType = IntrinsicTag | ComponentType;
  interface ElementClass {
    render(): UiChild;
  }
  interface IntrinsicAttributes {
    key?: string | number;
  }
  interface ElementChildrenAttribute {
    children: {};
  }
  interface IntrinsicElements {
    text: WithChildren<TextProps, TextChildren>;
    editabletext: EditableTextProps & {
      children?: never;
    };
    button: WithChildren<ButtonProps, JsxChildren | TextChildren>;
    box: WithChildren<BoxProps>;
    stack: WithChildren<StackProps>;
    row: WithChildren<RowProps>;
    column: WithChildren<ColumnProps>;
    scrollview: WithChildren<ScrollViewProps>;
    grid: WithChildren<GridProps>;
  }
  type LibraryManagedAttributes<C, P> = C extends ClassComponent ? ComponentProps<C> : C extends ((props: infer I, ...rest: any[]) => UiChild) ? unknown extends I ? ComponentProps<C> : I extends Record<string, InputCell<any>> ? ComponentProps<C> : P : P;
}
type JsxProps = Record<string, unknown> & {
  children?: JsxChildren;
};
declare function jsx(type: JSX.ElementType, props: JsxProps | null, key?: string | number): JSX.Element;
declare const jsxs: typeof jsx;
declare function jsxDEV(type: JSX.ElementType, props: JsxProps | null, key?: string | number): JSX.Element;
declare function Fragment(_props: {
  children?: JsxChildren;
}): never;
export {
  Fragment,
  IntrinsicTag,
  jsx,
  JSX,
  JsxChild,
  JsxChildren,
  jsxDEV,
  jsxs,
  type Component,
  type ComponentContext
};
