// API report for @gesso/framework.
//
// Generated by `pnpm api:update` from the declarations tsdown emits, with
// comments stripped and chunk hashes normalised. Committed so that a change
// to the public surface is a reviewable diff. Do not edit by hand.

// ==== FunctionComponent.d.ts ====
import {
  BehaviorSubject,
  Observable
} from "rxjs";
import {
  Reactive,
  UiChild
} from "@gesso/core";
declare abstract class Component {
  onMount?(): void;
  onUnmount?(): void;
  abstract render(): UiChild;
}
declare class InputCell<T> extends BehaviorSubject<T> {
  constructor(initialValue: T);
  get value(): T;
}
declare function input<T>(initialValue: T): InputCell<T>;
declare function input<T>(source: InputCell<T | undefined>, fallback: T): InputCell<T>;
type Command = (...args: never[]) => void;
type CommandMap = Record<string, Command>;
interface ChannelToken<View extends object, Commands extends object = Record<string, never>> {
  readonly name: string;
  readonly initial: View;
  readonly commands?: Commands;
}
declare function channel<View extends object, Commands extends object = Record<string, never>>(name: string, initial: View): ChannelToken<View, Commands>;
declare function viewKeys(token: {
  initial: object;
}): string[];
type PatchPath = readonly (string | number)[];
type Patch = {
  op: 'set';
  projection: string;
  path: PatchPath;
  value: unknown;
} | {
  op: 'delete';
  projection: string;
  path: PatchPath;
} | {
  op: 'splice';
  projection: string;
  path: PatchPath;
  index: number;
  deleteCount: number;
  items: readonly unknown[];
};
declare function diffProjection(projection: string, previous: unknown, current: unknown): Patch[];
declare function applyPatches(root: unknown, patches: readonly Patch[]): unknown;
declare function applyPatch(root: unknown, patch: Patch): unknown;
interface ChannelPort {
  postMessage(message: unknown): void;
  onmessage: ((event: {
    data: unknown;
  }) => void) | null;
}
type ChannelClientMessage = {
  type: 'channel:sync';
} | {
  type: 'channel:command';
  command: string;
  payload: unknown;
};
type ChannelHostMessage = {
  type: 'channel:patch';
  patches: Patch[];
} | {
  type: 'channel:error';
  message: string;
  stack?: string;
};
declare function isChannelClientMessage(value: unknown): value is ChannelClientMessage;
declare function isChannelHostMessage(value: unknown): value is ChannelHostMessage;
declare class ChannelReplica<View extends object, Commands extends object> {
  private readonly token;
  private readonly port;
  private readonly cells;
  private readonly commandProxy;
  private errorListener;
  private pending;
  private scheduleFlush;
  constructor(token: ChannelToken<View, Commands>, port: ChannelPort);
  get view(): { readonly [K in keyof View]: InputCell<View[K]>; };
  get send(): Commands;
  private readonly viewProxy;
  private createCommandProxy;
  onError(listener: ((message: string, stack?: string) => void) | null): void;
  private receive;
  private report;
  deferPatches(scheduleFlush: () => void): void;
  get hasPendingPatches(): boolean;
  flush(): void;
  applyPatches(patches: readonly Patch[]): void;
  private post;
  dispose(): void;
}
interface ComponentContext {
  inject<S extends object>(ServiceClass: new () => S): S;
  channel<V extends object, C extends object>(token: ChannelToken<V, C>): ChannelReplica<V, C>;
  onMount(hook: () => void): void;
  onUnmount(hook: () => void): void;
}
type Inputs<P> = { readonly [K in keyof P]-?: InputCell<P[K]>; };
type FunctionComponent<P = {}> = (props: Inputs<P>, context: ComponentContext) => UiChild;
type ClassComponent = new () => Component;
type ComponentType = ClassComponent | ((props: any, context: ComponentContext) => UiChild);
type IsAny<T> = 0 extends 1 & T ? true : false;
type CellValue<C> = C extends InputCell<infer T> ? T : never;
type OptionalCellKeys<I> = { [K in keyof I]: undefined extends CellValue<I[K]> ? K : never; }[keyof I];
type PropsForCells<I> = [keyof I] extends [never] ? NoProps : { [K in OptionalCellKeys<I>]?: Reactive<CellValue<I[K]>>; } & { [K in Exclude<keyof I, OptionalCellKeys<I>>]: Reactive<CellValue<I[K]>>; };
type NoProps = {
  readonly __noProps?: never;
};
type InputFields<I> = { [K in keyof I as I[K] extends InputCell<any> ? K : never]: I[K]; };
type ComponentProps<C> = C extends ClassComponent ? Partial<PropsForCells<InputFields<InstanceType<C>>>> : C extends ((props: infer I, ...rest: any[]) => UiChild) ? IsAny<I> extends true ? Record<string, unknown> : unknown extends I ? NoProps : [I] extends [undefined] ? NoProps : PropsForCells<I> : never;
type RequiredKeys<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? never : K; }[keyof T];
type ComponentArgs<C> = RequiredKeys<ComponentProps<C>> extends never ? [props?: ComponentProps<C>, key?: string | number] : [props: ComponentProps<C>, key?: string | number];
declare function isClassComponent(component: ComponentType): component is ClassComponent;
export {
  applyPatch,
  applyPatches,
  channel,
  ChannelClientMessage,
  ChannelHostMessage,
  ChannelPort,
  ChannelReplica,
  ChannelToken,
  ClassComponent,
  Command,
  CommandMap,
  Component,
  ComponentArgs,
  ComponentContext,
  ComponentProps,
  ComponentType,
  diffProjection,
  FunctionComponent,
  input,
  InputCell,
  Inputs,
  isChannelClientMessage,
  isChannelHostMessage,
  isClassComponent,
  Patch,
  PatchPath,
  viewKeys
};
// ==== index.d.ts ====
import {
  applyPatch,
  applyPatches,
  channel,
  ChannelClientMessage,
  ChannelHostMessage,
  ChannelPort,
  ChannelReplica,
  ChannelToken,
  ClassComponent,
  Command,
  CommandMap,
  Component,
  ComponentArgs,
  ComponentContext,
  ComponentProps,
  ComponentType,
  diffProjection,
  FunctionComponent,
  input,
  InputCell,
  Inputs,
  isChannelClientMessage,
  isChannelHostMessage,
  isClassComponent,
  Patch,
  PatchPath,
  viewKeys
} from "./FunctionComponent-Bjd3Lj5d.js";
import {
  BehaviorSubject,
  Observable,
  Subscription
} from "rxjs";
import {
  AnimatedCell,
  AnimationDriver,
  CanvasHost,
  ComponentLikeElement,
  ComponentResolver,
  EditingState,
  EditingState as EditingState$1,
  IconRasterizer,
  ImageResolver,
  LayoutExplanation,
  LayoutInspector,
  RendererBackend,
  TextMeasurer,
  UI_ROLES,
  UI_SEMANTIC_STATES,
  UiChild,
  UiDurationToken,
  UiEasing,
  UiEasingToken,
  UiEditingController,
  UiElement,
  UiFindController,
  UiFocusManager,
  UiFrameClockFactory,
  UiInputDispatcher,
  UiKeyboardController,
  UiKeyModifiers,
  UiMotion,
  UiNode,
  UiPlatformAdapter,
  UiPointerController,
  UiReducedMotionPolicy,
  UiRole,
  UiSelectionController,
  UiSemanticsAction,
  UiSemanticsMap,
  UiSemanticsMap as UiSemanticsMap$1,
  UiSemanticsPatch,
  UiSemanticsRecord,
  UiSemanticsRecord as UiSemanticsRecord$1,
  UiSemanticState,
  UiSemanticsUpdate,
  UiSpringSpec,
  UiSpringToken,
  UiWheelController
} from "@gesso/core";
declare class InternalState<T> extends BehaviorSubject<T> {
  constructor(initialValue: T);
  get value(): T;
  set value(next: T);
}
declare function internalState<T>(initialValue: T): InternalState<T>;
declare class ServiceRegistry {
  private readonly services;
  register<T extends object>(ServiceClass: new () => T): T;
  get<T extends object>(ServiceClass: new () => T): T;
  has(ServiceClass: Function): boolean;
}
declare function Define(tag: string): ClassDecorator;
declare function Input(): PropertyDecorator;
declare function Inject<T extends Function>(StoreClass: T): PropertyDecorator;
declare function Channel(token: {
  name: string;
}): PropertyDecorator;
interface ChannelSource<View extends object, Commands extends object> {
  view: { readonly [K in keyof View]: Observable<View[K]>; };
  commands?: Commands;
}
declare function provide<View extends object, Commands extends object>(token: ChannelToken<View, Commands>, source: ChannelSource<View, Commands>, port: ChannelPort): ProvidedChannel;
declare class ProvidedChannel {
  private readonly token;
  private readonly source;
  private readonly port;
  private readonly subscriptions;
  private readonly previous;
  private readonly checked;
  private synced;
  constructor(token: ChannelToken<object, CommandMap>, source: ChannelSource<object, CommandMap>, port: ChannelPort);
  private receive;
  private runCommand;
  private sync;
  private publish;
  private resend;
  private post;
  dispose(): void;
}
declare class ChannelRegistry {
  private readonly replicas;
  attach<View extends object, Commands extends object>(token: ChannelToken<View, Commands>, port: ChannelPort): ChannelReplica<View, Commands>;
  get<View extends object, Commands extends object>(token: ChannelToken<View, Commands>): ChannelReplica<View, Commands>;
  has(token: ChannelToken<object, CommandMap>): boolean;
  all(): ChannelReplica<object, CommandMap>[];
  dispose(): void;
}
declare function findUnplainPath(value: unknown, path?: readonly (string | number)[]): string | null;
declare function requirePlainData(channelName: string, key: string, value: unknown): void;
interface MessageEndpoint {
  postMessage(message: unknown): void;
  onmessage: ((event: {
    data: unknown;
  }) => void) | null;
}
interface PortHandshake {
  type: 'gesso:port';
  key: string;
}
declare function isPortHandshake(value: unknown): value is PortHandshake;
interface WorkerHandle {
  open(key: string): MessagePort;
  readonly spawned: boolean;
  terminate(): void;
}
declare const APPLICATION_WORKER: WorkerHandle;
interface TransferTarget {
  postMessage(message: unknown, transfer: Transferable[]): void;
}
declare function portHandle(endpoint: TransferTarget): WorkerHandle;
declare function workerHandle(factory: () => Worker): WorkerHandle;
interface PortHost {
  onmessage: ((event: {
    data: unknown;
    ports?: readonly MessagePort[];
  }) => void) | null;
}
interface PortErrorMessage {
  type: 'port:error';
  message: string;
}
declare function isPortErrorMessage(value: unknown): value is PortErrorMessage;
declare function servePorts(onPort: (key: string, port: MessagePort) => boolean, names: () => readonly string[], host?: PortHost): () => void;
interface ChannelRegistration {
  token: {
    name: string;
    initial: object;
  };
  worker?: WorkerHandle | (() => Worker);
  source?: {
    view: Record<string, Observable<unknown>>;
    commands?: Record<string, Command>;
  };
}
interface ChannelRegistryHandle {
  registry: ChannelRegistry;
  dispose(): void;
}
declare function createChannelRegistry(registrations: readonly ChannelRegistration[], onError?: (channelName: string, message: string, stack?: string) => void): ChannelRegistryHandle;
interface ServedChannel {
  token: {
    name: string;
    initial: object;
  };
  source: {
    view: Record<string, Observable<unknown>>;
    commands?: Record<string, Command>;
  };
}
declare function serveChannels(channels: readonly ServedChannel[], host?: PortHost): () => void;
declare function structurallyEqual<T>(a: T, b: T): boolean;
interface ComponentElement<P = Record<string, unknown>> {
  readonly kind: 'component';
  readonly tag: string;
  readonly component: ComponentType;
  readonly props: P;
  readonly key?: string | number;
}
declare function isComponentElement(value: unknown): value is ComponentElement;
type FrameworkChild = UiChild | ComponentElement;
declare function createComponent<C extends ComponentType>(component: C, ...args: ComponentArgs<C>): ComponentElement<ComponentProps<C>>;
type OverlayPlacement = 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end' | 'right' | 'right-start' | 'right-end';
interface OverlayEntry {
  readonly id: string;
  readonly content: UiChild;
  readonly anchor?: UiNode | null;
  readonly placement?: OverlayPlacement;
  readonly offset?: number;
  readonly top?: number;
  readonly right?: number;
  readonly bottom?: number;
  readonly left?: number;
  readonly dismissOnOutsidePress?: boolean;
  readonly zIndex?: number;
  readonly environment?: UiNode | null;
  readonly onClose?: () => void;
}
declare class OverlayService {
  readonly entries: InternalState<readonly OverlayEntry[]>;
  open(entry: OverlayEntry): void;
  close(id: string): void;
  closeAll(): void;
  isOpen(id: string): boolean;
}
declare class OverlayLayer extends Component {
  overlays: OverlayService;
  render(): UiElement;
  private renderEntries;
}
declare class ComponentHostResolver implements ComponentResolver {
  private readonly services;
  private readonly channels;
  private readonly hosts;
  private pendingMounts;
  constructor(services?: ServiceRegistry, channels?: ChannelRegistry);
  resolve(element: ComponentLikeElement, anchorId: string): UiChild;
  release(anchorId: string): void;
  flushMounts(): void;
  dispose(): void;
  get size(): number;
}
declare class ComponentHost<P extends Record<string, unknown> = Record<string, unknown>> {
  private readonly services;
  private readonly channels;
  readonly instance: Component | undefined;
  readonly element: ComponentElement<P>;
  readonly subscriptions: Subscription;
  private mounted;
  private output;
  private readonly inputSources;
  private readonly inputSubscriptions;
  private readonly functionalCells;
  private readonly mountHooks;
  private readonly unmountHooks;
  private rendering;
  constructor(element: ComponentElement<P>, services?: ServiceRegistry, channels?: ChannelRegistry);
  get component(): ComponentType;
  render(): UiChild;
  mount(): void;
  dispose(): void;
  updateProps(props: P): void;
  private renderFunction;
  private createInputRecord;
  private createContext;
  private wireInputs;
  private applyInput;
  private validateInputs;
  private wireChannels;
  private wireInjects;
}
type PatternSegment = {
  readonly kind: 'static';
  readonly text: string;
} | {
  readonly kind: 'param';
  readonly name: string;
} | {
  readonly kind: 'rest';
};
type RouteParams<Path extends string> = Prettify<ParamsOf<Path>>;
type ParamsOf<Path extends string> = Path extends `${infer Head}/${infer Rest}` ? ParamOfSegment<Head> & ParamsOf<Rest> : ParamOfSegment<Path>;
type ParamOfSegment<Segment extends string> = Segment extends `:${infer Name}` ? { [K in Name]: string; } : Segment extends '*' ? {
  rest: string;
} : {};
type Prettify<T> = { [K in keyof T]: T[K]; } & {};
type HasNoParams<Path extends string> = keyof ParamsOf<Path> extends never ? true : false;
declare function buildPath(pattern: string, params?: Readonly<Record<string, string>>): string;
interface ParsedUrl {
  readonly path: string;
  readonly query: Readonly<Record<string, string>>;
}
declare function parseUrl(url: string): ParsedUrl;
declare function formatUrl(path: string, query?: Readonly<Record<string, string>>): string;
interface OutletProps {
  readonly outlet: UiChild;
}
interface RouteTarget {
  readonly route: RouteDefinition;
  readonly params: Readonly<Record<string, string>>;
  readonly query: Readonly<Record<string, string>>;
}
interface RouteContext<Path extends string = string> {
  readonly params: RouteParams<Path>;
  readonly query: Readonly<Record<string, string>>;
  readonly url: string;
}
type RouteGuard<Path extends string = string> = (context: RouteContext<Path>) => boolean | RouteTarget;
interface RouteDefinition<Path extends string = string> {
  readonly path: Path;
  readonly component: ComponentType;
  readonly parent?: RouteDefinition;
  readonly guard?: RouteGuard<Path>;
  readonly segments: readonly PatternSegment[];
  readonly chain: readonly RouteDefinition[];
}
interface RouteOptions<Path extends string> {
  readonly path: Path;
  readonly component: ComponentType;
  readonly parent?: RouteDefinition;
  readonly guard?: RouteGuard<Path>;
}
declare function route<const Path extends string>(options: RouteOptions<Path>): RouteDefinition<Path>;
declare function to<Path extends string>(route: RouteDefinition<Path>, ...args: ToArgs<Path>): RouteTarget;
interface ToOptions {
  readonly query?: Readonly<Record<string, string>>;
}
type ToArgs<Path extends string> = HasNoParams<Path> extends true ? [] : [params: RouteParams<Path>, options?: ToOptions];
interface RouteMatch {
  readonly route: RouteDefinition;
  readonly chain: readonly RouteDefinition[];
  readonly params: Readonly<Record<string, string>>;
  readonly query: Readonly<Record<string, string>>;
  readonly path: string;
  readonly url: string;
}
interface RouterHistorySink {
  push(url: string): void;
  replace(url: string): void;
  back(): void;
  forward(): void;
}
interface RouterRoutes {
  readonly routes: readonly RouteDefinition[];
  readonly notFound?: RouteDefinition;
}
interface NavigateOptions {
  readonly query?: Readonly<Record<string, string>>;
  readonly replace?: boolean;
}
type GoArgs<Path extends string> = HasNoParams<Path> extends true ? [options?: NavigateOptions] : [params: RouteParams<Path>, options?: NavigateOptions];
declare class RouterService {
  readonly url: InternalState<string>;
  readonly match: InternalState<RouteMatch | null>;
  private routes;
  private notFound;
  private history;
  setHistory(history: RouterHistorySink | null): void;
  setRoutes(routes: RouterRoutes): void;
  get declaredRoutes(): readonly RouteDefinition[];
  go<Path extends string>(route: RouteDefinition<Path>, ...args: GoArgs<Path>): void;
  navigate(url: string, options?: {
    replace?: boolean;
  }): void;
  back(): void;
  forward(): void;
  applyUrl(url: string): void;
  params<Path extends string>(route: RouteDefinition<Path>): RouteParams<Path> | null;
  observeParams<Path extends string>(route: RouteDefinition<Path>): Observable<RouteParams<Path> | null>;
  isActive(route: RouteDefinition): Observable<boolean>;
  private resolveInto;
  private publish;
  private resolve;
  private runGuards;
}
type ShellHistoryMode = 'path' | 'hash' | 'memory';
interface ShellHistoryOptions {
  readonly mode?: ShellHistoryMode;
  readonly base?: string;
  readonly initialUrl?: string;
}
interface ShellHistory {
  readonly url: string;
  push(url: string): void;
  replace(url: string): void;
  back(): void;
  forward(): void;
  onChange(listener: (url: string) => void): void;
  dispose(): void;
}
interface HistoryWindow {
  readonly location: {
    pathname: string;
    search: string;
    hash: string;
  };
  readonly history: {
    pushState(data: unknown, title: string, url: string): void;
    replaceState(data: unknown, title: string, url: string): void;
    back(): void;
    forward(): void;
  };
  addEventListener(type: string, listener: () => void): void;
  removeEventListener(type: string, listener: () => void): void;
}
declare function createShellHistory(options?: ShellHistoryOptions, host?: HistoryWindow | undefined): ShellHistory;
type ShellRequest = {
  type: 'clipboard';
  text: string;
} | {
  type: 'openUrl';
  url: string;
} | {
  type: 'history';
  action: 'push' | 'replace';
  url: string;
} | {
  type: 'history';
  action: 'back' | 'forward';
  url?: undefined;
};
declare class ShellService {
  private handler;
  setHandler(handler: ((request: ShellRequest) => void) | null): void;
  copyText(text: string): void;
  openUrl(url: string): void;
}
declare const UI_FRAME_PHASES: readonly ['ticks', 'patches', 'environment', 'virtualize', 'layout', 'semantics', 'render'];
type UiFramePhase = (typeof UI_FRAME_PHASES)[number];
type FramePhaseTimings = Record<UiFramePhase, number>;
interface RuntimeInput {
  readonly dispatcher: UiInputDispatcher;
  readonly pointer: UiPointerController;
  readonly wheel: UiWheelController;
  readonly keyboard: UiKeyboardController;
  readonly focus: UiFocusManager;
  readonly editing: UiEditingController;
  readonly selection: UiSelectionController;
  readonly find: UiFindController;
}
type RendererChoice = RendererBackend | 'auto';
interface GessoRuntimeOptions {
  root: FrameworkChild;
  canvas: CanvasHost;
  renderer?: RendererChoice;
  measureCanvas?: CanvasHost;
  textMeasurer?: TextMeasurer;
  media?: {
    resolver?: ImageResolver;
    rasterizer?: IconRasterizer;
  };
  services?: ServiceRegistry;
  routes?: RouterRoutes;
  channels?: ChannelRegistry;
  clock?: UiFrameClockFactory;
  width?: number;
  height?: number;
  dpr?: number;
}
declare class GessoRuntime {
  readonly services: ServiceRegistry;
  readonly channels: ChannelRegistry;
  readonly input: RuntimeInput;
  readonly inspector: LayoutInspector;
  private readonly resolver;
  private readonly graph;
  private readonly engine;
  private readonly builder;
  private readonly scheduler;
  private readonly inputLatency;
  private readonly canvas;
  private readonly textMeasurer;
  private canvasSurface;
  private renderer;
  private rendererState;
  readonly rendererReady: Promise<RendererBackend>;
  private readonly dispatcher;
  private width;
  private height;
  private root;
  private appRoot;
  private constraints;
  private pixelRatio;
  private lastFrameMs;
  private frameListener;
  private rendererErrorListener;
  private gpuTimings;
  private inspectListener;
  private lastInspection;
  private cursorListener;
  private lastCursor;
  private editingListener;
  private selectionController;
  private findController;
  private readonly focusManager;
  private readonly layoutNotifier;
  private readonly animations;
  private readonly focusNotifier;
  private readonly environmentNotifier;
  private semantics;
  private semanticsListener;
  private semanticsBoxes;
  private lastFocusedId;
  private lastEditingState;
  private shellListener;
  private caretTimer;
  private scrollbarTimer;
  private inspectorTimer;
  private animationTimer;
  private replicas;
  private phaseTimings;
  private started;
  constructor(options: GessoRuntimeOptions);
  deferPatchesFrom(sources: readonly PatchSource[]): void;
  start(): void;
  get rendererBackend(): RendererBackend | 'pending';
  onRendererError(listener: ((message: string) => void) | null): void;
  onListenerError(listener: ((message: string, stack?: string) => void) | null): void;
  private reportRendererError;
  private fallBackToCanvas2D;
  private requestRepaint;
  resize(width: number, height: number, dpr?: number): void;
  onFrame(listener: ((metrics: FrameMetrics) => void) | null): void;
  noteInput(at: number | undefined): void;
  setInspectorEnabled(enabled: boolean): void;
  onInspect(listener: ((text: string | null) => void) | null): void;
  onCursor(listener: ((cursor: string | null) => void) | null): void;
  get cursor(): string | null;
  onEditingState(listener: ((state: EditingState$1 | null) => void) | null): void;
  get editingState(): EditingState$1 | null;
  onShellRequest(listener: ((request: ShellRequest) => void) | null): void;
  setTextInputSource(source: 'proxy' | 'keys'): void;
  setVisible(visible: boolean): void;
  setReducedMotion(reduced: boolean): void;
  setUrl(url: string): void;
  get reducedMotion(): boolean;
  explain(node: UiNode): LayoutExplanation;
  debugRoot(): UiNode;
  debugLayoutBox(node: UiNode): {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  layoutRoot(): UiNode;
  scrollIntoView(node: UiNode, padding?: number): void;
  dispose(): void;
  private buildRoot;
  private resolveRootElement;
  private createInput;
  onSemantics(listener: ((update: UiSemanticsUpdate) => void) | null): void;
  semanticsTree(): UiSemanticsMap$1;
  applySemanticsAction(action: UiSemanticsAction): void;
  private updateSemantics;
  private collectSemanticsBoxes;
  private revealBox;
  private handleHoverChange;
  private createScrollSink;
  private runPreCollectPhases;
  private hasVirtualWindows;
  private updateVirtualWindows;
  private collectVirtualMeasures;
  private extentOf;
  private handleFrame;
  private scheduleAnimationTick;
  private scheduleScrollbarFade;
  private scheduleCaretBlink;
  private sendEditingState;
  private scheduleInspectorRepaint;
  private sendCursor;
  private sendInspection;
  private timePhase;
  get lastFrameDurationMs(): number;
}
interface PatchSource {
  readonly hasPendingPatches: boolean;
  flush(): void;
  deferPatches(scheduleFlush: () => void): void;
}
interface FrameMetrics {
  frame: number;
  durationMs: number;
  nodes: number;
  measured: number;
  relayoutRoots: number;
  phases: FramePhaseTimings;
  renderer: RendererBackend | 'pending';
  gpu: GpuStageTimings | null;
  at: number;
  inputLatencyMs: number | null;
}
interface GpuStageTimings {
  prepare: number;
  upload: number;
  encode: number;
}
declare class GessoAppBuilder {
  private readonly root;
  private readonly channelRegistrations;
  private readonly serviceRegistrations;
  private frameListener;
  private inspectListener;
  private errorListener;
  private rendererChoice;
  private routes;
  private historyOptions;
  private app;
  constructor(root: FrameworkChild | ComponentType);
  useChannel<V extends object, C extends object>(token: ChannelToken<V, C>, options: {
    worker?: WorkerHandle | (() => Worker);
    source?: ChannelSource<V, C>;
  }): this;
  useService(ServiceClass: new () => object): this;
  useRoutes(routes: RouterRoutes): this;
  useHistory(history: ShellHistoryOptions): this;
  renderer(choice: RendererChoice): this;
  onFrame(listener: (metrics: FrameMetrics) => void): this;
  onInspect(listener: (text: string | null) => void): this;
  onError(listener: (message: string, stack: string | undefined, source: 'renderer' | 'listener') => void): this;
  setInspector(enabled: boolean): void;
  mountSync(host: HTMLElement | string): () => void;
}
type ShellToRuntimeMessage = {
  type: 'init';
  canvas: OffscreenCanvas;
  width: number;
  height: number;
  dpr: number;
  renderer?: RendererChoice;
  textInput?: 'proxy' | 'keys';
  appPort?: MessagePort;
  accessibility?: boolean;
} | {
  type: 'resize';
  width: number;
  height: number;
  dpr: number;
} | {
  type: 'pointerDown';
  x: number;
  y: number;
  buttons: number;
  modifiers: UiKeyModifiers;
  at?: number;
} | {
  type: 'pointerMove';
  x: number;
  y: number;
  buttons: number;
  modifiers: UiKeyModifiers;
  at?: number;
} | {
  type: 'pointerUp';
  x: number;
  y: number;
  buttons: number;
  modifiers: UiKeyModifiers;
  at?: number;
} | {
  type: 'pointerCancel';
  at?: number;
} | {
  type: 'wheel';
  x: number;
  y: number;
  deltaX: number;
  deltaY: number;
  modifiers: UiKeyModifiers;
  at?: number;
} | {
  type: 'keyDown';
  key: string;
  modifiers: UiKeyModifiers;
  at?: number;
} | {
  type: 'keyUp';
  key: string;
  modifiers: UiKeyModifiers;
  at?: number;
} |
{
  type: 'beforeInput';
  inputType: string;
  data: string | null;
  at?: number;
} | {
  type: 'compositionStart';
  at?: number;
} |
{
  type: 'compositionUpdate';
  text: string;
  caret: number;
  at?: number;
} |
{
  type: 'compositionEnd';
  text: string;
  at?: number;
} | {
  type: 'paste';
  text: string;
  at?: number;
} |
{
  type: 'blur';
} |
{
  type: 'visibility';
  visible: boolean;
} |
{
  type: 'reducedMotion';
  reduced: boolean;
} |
{
  type: 'url';
  url: string;
} | {
  type: 'inspector';
  enabled: boolean;
} |
{
  type: 'semanticsAction';
  action: UiSemanticsAction;
} | {
  type: 'dispose';
};
type RuntimeErrorSource = 'message' | 'uncaught' | 'renderer' | 'channel' | 'listener';
type RuntimeToShellMessage = {
  type: 'ready';
} | {
  type: 'frame';
  frame: number;
  durationMs: number;
  nodes: number;
  measured: number;
  relayoutRoots: number;
  at: number;
  inputLatencyMs: number | null;
  phases: FramePhaseTimings;
  renderer: RendererBackend | 'pending';
  gpu: GpuStageTimings | null;
} | {
  type: 'error';
  message: string;
  stack?: string;
  source: RuntimeErrorSource;
} |
{
  type: 'inspect';
  text: string | null;
} |
{
  type: 'cursor';
  cursor: string | null;
} |
{
  type: 'editing';
  state: EditingState$1 | null;
} |
{
  type: 'clipboard';
  text: string;
} |
{
  type: 'openUrl';
  url: string;
} |
{
  type: 'history';
  action: 'push' | 'replace' | 'back' | 'forward';
  url?: string;
} |
{
  type: 'semantics';
  update: UiSemanticsUpdate;
};
interface WorkerAppOptions {
  renderWorker: (() => Worker) | URL | string;
  renderer?: RendererChoice;
  onFrame?: (metrics: FrameMetrics) => void;
  appLogicWorker?: Worker | (() => Worker) | URL | string;
  onError?: (message: string, stack: string | undefined, source: RuntimeErrorSource) => void;
  onInspect?: (text: string | null) => void;
  interceptFind?: boolean;
  accessibility?: boolean;
  history?: ShellHistoryOptions;
}
declare class WorkerApp {
  private readonly options;
  private renderWorker;
  private appLogicWorker;
  private ownsAppLogicWorker;
  private canvas;
  private host;
  private resizeObserver;
  private detachInput;
  private proxy;
  private mirror;
  private history;
  private ready;
  constructor(options: WorkerAppOptions);
  mount(host: HTMLElement | string): () => void;
  private handleWorkerFailure;
  private report;
  private forwardKeyDown;
  private forwardKeyUp;
  setInspector(enabled: boolean): void;
  dispose(): void;
  private readonly handleWorkerMessage;
  private attachHistory;
  private applyHistory;
  private post;
  private observeResize;
  private attachInput;
}
declare function createApp(options: WorkerAppOptions): WorkerApp;
declare function createApp(root: FrameworkChild | ComponentType): GessoAppBuilder;
interface GessoAppOptions {
  host: HTMLElement;
  root: FrameworkChild;
  services?: ServiceRegistry;
  channels?: ChannelRegistry;
  routes?: RouterRoutes;
  history?: ShellHistoryOptions;
  canvas?: CanvasHost;
  renderer?: RendererChoice;
  clock?: UiFrameClockFactory;
  input?: boolean;
  accessibility?: boolean;
}
declare class GessoApp {
  private readonly runtime;
  private readonly canvas;
  private readonly host;
  private readonly inputEnabled;
  private readonly accessibilityEnabled;
  private readonly adapter;
  private readonly historyOptions;
  private running;
  private resizeObserver;
  private proxy;
  private mirror;
  private history;
  private detachVisibility;
  private detachReducedMotion;
  constructor(options: GessoAppOptions);
  get services(): ServiceRegistry;
  get input(): UiPlatformAdapter;
  mount(): void;
  deferPatchesFrom(sources: readonly PatchSource[]): void;
  onFrame(listener: ((metrics: FrameMetrics) => void) | null): void;
  get rendererReady(): Promise<'canvas2d' | 'webgpu'>;
  resize(width: number, height: number): void;
  setInspector(enabled: boolean): void;
  onInspect(listener: ((text: string | null) => void) | null): void;
  onError(listener: ((message: string, stack: string | undefined, source: 'renderer' | 'listener') => void) | null): void;
  debugRoot(): UiNode;
  dispose(): void;
  private attachInput;
  private attachSemanticsMirror;
  private attachHistory;
  private handleShellRequest;
  private observeResize;
}
declare class RouterOutlet extends Component {
  router: RouterService;
  render(): UiChild;
}
type UiDuration = UiDurationToken | number;
type UiEasingChoice = UiEasingToken | UiEasing;
interface AnimateOptions {
  duration?: UiDuration;
  easing?: UiEasingChoice;
  stepMs?: number;
  repeat?: boolean;
  reducedMotion?: UiReducedMotionPolicy;
}
interface SpringOptions {
  spring?: UiSpringToken | UiSpringSpec;
  stiffness?: number;
  damping?: number;
  mass?: number;
  velocity?: number;
  restDelta?: number;
  reducedMotion?: UiReducedMotionPolicy;
}
declare class AnimationService {
  readonly reducedMotion: InternalState<boolean>;
  private driver;
  private motionVocabulary;
  setDriver(driver: AnimationDriver | null): void;
  setMotion(motion: UiMotion): void;
  get motion(): UiMotion;
  applyReducedMotion(reduced: boolean): void;
  animate<T>(cell: AnimatedCell<T>, to: T, options?: AnimateOptions): Observable<T>;
  spring(cell: AnimatedCell<number>, to: number, options?: SpringOptions): Observable<number>;
  stop<T>(cell: AnimatedCell<T>): boolean;
  private resolveDuration;
  private resolveEasing;
}
declare function observeReducedMotion(onChange: (reduced: boolean) => void): () => void;
declare class FindService {
  readonly open: InternalState<boolean>;
  readonly query: InternalState<string>;
  readonly matchCount: InternalState<number>;
  readonly activeMatch: InternalState<number>;
  private controller;
  private detach;
  private field;
  setController(controller: UiFindController | null): void;
  setField(node: UiNode | null): void;
  openFind(): void;
  close(): void;
  search(query: string, matchCase?: boolean): void;
  next(): void;
  previous(): void;
  refresh(): void;
  private sync;
}
declare class MediaService {
  private imageResolver;
  private iconRasterizer;
  private ownsResolver;
  get images(): ImageResolver;
  get icons(): IconRasterizer;
  setResolver(resolver: ImageResolver): void;
  setRasterizer(rasterizer: IconRasterizer): void;
  dispose(): void;
}
declare class FocusService {
  readonly focused: InternalState<UiNode | null>;
  readonly trapped: InternalState<boolean>;
  private manager;
  private detach;
  private queued;
  setManager(manager: UiFocusManager | null): void;
  focus(node: UiNode): void;
  blur(): void;
  focusNext(): void;
  focusPrevious(): void;
  trap(scope: UiNode): void;
  releaseTrap(): void;
  private run;
  private sync;
}
interface EditingProxySink {
  beforeInput(inputType: string, data: string | null): void;
  compositionStart(): void;
  compositionUpdate(text: string, caret: number): void;
  compositionEnd(text: string): void;
  paste(text: string): void;
  blur(): void;
  keyDown?(event: KeyboardEvent): void;
  keyUp?(event: KeyboardEvent): void;
}
declare class EditingProxy {
  private readonly canvas;
  private readonly sink;
  private readonly textarea;
  private readonly doc;
  private readonly view;
  private state;
  private composing;
  private disposed;
  private readonly detach;
  constructor(canvas: HTMLCanvasElement, sink: EditingProxySink);
  get active(): boolean;
  get element(): HTMLTextAreaElement;
  update(state: EditingState$1 | null): void;
  focus(): void;
  describe(record: UiSemanticsRecord$1 | null): void;
  dispose(): void;
  private position;
  private mirror;
  private listen;
}
declare function writeClipboard(text: string, doc?: Document): void;
interface SemanticsMirrorSink {
  action(action: UiSemanticsAction): void;
  keyDown?(event: KeyboardEvent): void;
  keyUp?(event: KeyboardEvent): void;
}
interface EditingMirrorTarget {
  readonly active: boolean;
  describe(record: UiSemanticsRecord$1 | null): void;
  focus(): void;
}
declare class SemanticsMirror {
  private readonly canvas;
  private readonly sink;
  private readonly editing;
  private readonly container;
  private readonly doc;
  private readonly entries;
  private readonly ids;
  private readonly detach;
  private resizeObserver;
  private stopTracking;
  private applying;
  private focusedId;
  private disposed;
  constructor(canvas: HTMLCanvasElement, sink: SemanticsMirrorSink, editing?: EditingMirrorTarget | null);
  get element(): HTMLElement;
  elementFor(id: string): HTMLElement | undefined;
  apply(update: UiSemanticsUpdate): void;
  dispose(): void;
  private upsert;
  private createElement;
  private describe;
  private place;
  private remove;
  private applyFocus;
  private listen;
  private idOf;
  private trackCanvas;
}
interface WorkerErrorEvent {
  message?: string;
  error?: unknown;
  filename?: string;
  lineno?: number;
  colno?: number;
}
interface WorkerRejectionEvent {
  reason?: unknown;
}
interface WorkerGlobal {
  onmessage: ((event: MessageEvent<ShellToRuntimeMessage>) => void) | null;
  postMessage(message: RuntimeToShellMessage): void;
  addEventListener(type: 'error', listener: (event: WorkerErrorEvent) => void): void;
  addEventListener(type: 'unhandledrejection', listener: (event: WorkerRejectionEvent) => void): void;
}
declare function renderRoot(root: FrameworkChild | ComponentType): RenderWorkerApp;
declare class RenderWorkerApp {
  private readonly channelRegistrations;
  private readonly serviceRegistrations;
  private routes;
  private readonly root;
  private readonly host;
  private runtime;
  private channels;
  private appLogicWorker;
  constructor(root: FrameworkChild | ComponentType, host?: WorkerGlobal);
  private reportUncaught;
  useChannel<V extends object, C extends object>(token: ChannelToken<V, C>, options?: {
    worker?: WorkerHandle | (() => Worker);
    source?: ChannelSource<V, C>;
  }): this;
  useService(ServiceClass: new () => object): this;
  useRoutes(routes: RouterRoutes): this;
  receive(message: ShellToRuntimeMessage): void;
  private dispatch;
  private resolveWorker;
  private initialize;
}
export {
  AnimationService,
  APPLICATION_WORKER,
  applyPatch,
  applyPatches,
  buildPath,
  channel,
  Channel,
  ChannelRegistry,
  ChannelReplica,
  Component,
  ComponentHost,
  ComponentHostResolver,
  createApp,
  createChannelRegistry,
  createComponent,
  createShellHistory,
  Define,
  diffProjection,
  EditingProxy,
  FindService,
  findUnplainPath,
  FocusService,
  formatUrl,
  GessoApp,
  GessoAppBuilder,
  GessoRuntime,
  Inject,
  input,
  Input,
  InputCell,
  internalState,
  InternalState,
  isChannelClientMessage,
  isChannelHostMessage,
  isClassComponent,
  isComponentElement,
  isPortErrorMessage,
  isPortHandshake,
  MediaService,
  observeReducedMotion,
  OverlayLayer,
  OverlayService,
  parseUrl,
  portHandle,
  provide,
  ProvidedChannel,
  renderRoot,
  RenderWorkerApp,
  requirePlainData,
  route,
  RouterOutlet,
  RouterService,
  SemanticsMirror,
  serveChannels,
  servePorts,
  ServiceRegistry,
  ShellService,
  structurallyEqual,
  to,
  type AnimateOptions,
  type ChannelClientMessage,
  type ChannelHostMessage,
  type ChannelPort,
  type ChannelRegistration,
  type ChannelRegistryHandle,
  type ChannelSource,
  type ChannelToken,
  type ClassComponent,
  type Command,
  type CommandMap,
  type ComponentContext,
  type ComponentElement,
  type ComponentProps,
  type ComponentType,
  type EditingMirrorTarget,
  type EditingProxySink,
  type EditingState,
  type FrameMetrics,
  type FramePhaseTimings,
  type FrameworkChild,
  type FunctionComponent,
  type GessoAppOptions,
  type GessoRuntimeOptions,
  type Inputs,
  type MessageEndpoint,
  type OutletProps,
  type OverlayEntry,
  type OverlayPlacement,
  type Patch,
  type PatchPath,
  type PortHandshake,
  type PortHost,
  type RendererChoice,
  type RouteContext,
  type RouteDefinition,
  type RouteGuard,
  type RouteMatch,
  type RouteOptions,
  type RouteParams,
  type RouterHistorySink,
  type RouterRoutes,
  type RouteTarget,
  type RuntimeErrorSource,
  type RuntimeInput,
  type RuntimeToShellMessage,
  type SemanticsMirrorSink,
  type ServedChannel,
  type ShellHistory,
  type ShellHistoryMode,
  type ShellHistoryOptions,
  type ShellRequest,
  type ShellToRuntimeMessage,
  type SpringOptions,
  type UiDuration,
  type UiEasingChoice,
  type UiFramePhase,
  type UiRole,
  type UiSemanticsMap,
  type UiSemanticsPatch,
  type UiSemanticsRecord,
  type UiSemanticState,
  type WorkerAppOptions,
  type WorkerHandle,
  UI_FRAME_PHASES,
  UI_ROLES,
  UI_SEMANTIC_STATES,
  viewKeys,
  WorkerApp,
  workerHandle,
  writeClipboard
};
// ==== jsx/jsx-dev-runtime.d.ts ====
import {
  Fragment,
  jsx,
  JSX,
  jsxDEV,
  jsxs
} from "./jsx-runtime.js";
export {
  Fragment,
  jsx,
  jsxDEV,
  jsxs,
  type JSX
};
// ==== jsx/jsx-runtime.d.ts ====
import {
  ClassComponent,
  Component,
  ComponentContext,
  ComponentProps,
  ComponentType,
  InputCell
} from "../FunctionComponent-Bjd3Lj5d.js";
import {
  Observable
} from "rxjs";
import {
  BoxProps,
  ButtonProps,
  ColumnProps,
  ComponentLikeElement,
  EditableTextProps,
  GridProps,
  RowProps,
  ScrollViewProps,
  StackProps,
  TextProps,
  UiChild,
  UiElement,
  UiNodeType
} from "@gesso/core";
type JsxChild = UiChild | string | number | boolean | null | undefined;
type JsxChildren = JsxChild | readonly JsxChildren[];
type WithChildren<P, C = JsxChildren> = P & {
  children?: C;
};
type TextChildren = string | number | Observable<string | number>;
declare const INTRINSIC_TYPES: {
  readonly text: UiNodeType.Text;
  readonly editabletext: UiNodeType.EditableText;
  readonly button: UiNodeType.Button;
  readonly box: UiNodeType.Box;
  readonly stack: UiNodeType.Box;
  readonly row: UiNodeType.Row;
  readonly column: UiNodeType.Column;
  readonly scrollview: UiNodeType.ScrollView;
  readonly grid: UiNodeType.Grid;
};
type IntrinsicTag = keyof typeof INTRINSIC_TYPES;
declare namespace JSX {
  type Element = UiElement | ComponentLikeElement;
  type ElementType = IntrinsicTag | ComponentType;
  interface ElementClass {
    render(): UiChild;
  }
  interface IntrinsicAttributes {
    key?: string | number;
  }
  interface ElementChildrenAttribute {
    children: {};
  }
  interface IntrinsicElements {
    text: WithChildren<TextProps, TextChildren>;
    editabletext: EditableTextProps & {
      children?: never;
    };
    button: WithChildren<ButtonProps, JsxChildren | TextChildren>;
    box: WithChildren<BoxProps>;
    stack: WithChildren<StackProps>;
    row: WithChildren<RowProps>;
    column: WithChildren<ColumnProps>;
    scrollview: WithChildren<ScrollViewProps>;
    grid: WithChildren<GridProps>;
  }
  type LibraryManagedAttributes<C, P> = C extends ClassComponent ? ComponentProps<C> : C extends ((props: infer I, ...rest: any[]) => UiChild) ? unknown extends I ? ComponentProps<C> : I extends Record<string, InputCell<any>> ? ComponentProps<C> : P : P;
}
type JsxProps = Record<string, unknown> & {
  children?: JsxChildren;
};
declare function jsx(type: JSX.ElementType, props: JsxProps | null, key?: string | number): JSX.Element;
declare const jsxs: typeof jsx;
declare function jsxDEV(type: JSX.ElementType, props: JsxProps | null, key?: string | number): JSX.Element;
declare function Fragment(_props: {
  children?: JsxChildren;
}): never;
export {
  Fragment,
  IntrinsicTag,
  jsx,
  JSX,
  JsxChild,
  JsxChildren,
  jsxDEV,
  jsxs,
  type Component,
  type ComponentContext
};
