// API report for @gesso/components.
//
// Generated by `pnpm api:update` from the declarations tsdown emits, with
// comments stripped and chunk hashes normalised. Committed so that a change
// to the public surface is a reviewable diff. Do not edit by hand.

// ==== index.d.ts ====
import {
  Observable
} from "rxjs";
import {
  ObjectFit,
  UiChild,
  UiColorValue,
  UiKeyboardEvent,
  UiLength,
  UiModifier,
  UiNode,
  UiNodeRef,
  UiSelfAlignment,
  UiTrackSize,
  UiVirtualWindow
} from "@gesso/core";
import {
  ComponentContext,
  InputCell,
  Inputs,
  OverlayPlacement
} from "@gesso/framework";
type Keymap = Readonly<Record<string, (event: UiKeyboardEvent) => void>>;
declare function keymap(bindings: Keymap): (event: UiKeyboardEvent) => void;
declare function quantize(value: number, min: number, max: number, step: number): number;
interface ControlLayoutProps {
  width?: UiLength;
  height?: UiLength;
  minWidth?: UiLength;
  minHeight?: UiLength;
  maxWidth?: UiLength;
  maxHeight?: UiLength;
  margin?: number;
  marginTop?: number;
  marginRight?: number;
  marginBottom?: number;
  marginLeft?: number;
  flex?: number;
  flexGrow?: number;
  flexShrink?: number;
  flexBasis?: UiLength;
  selfX?: UiSelfAlignment;
  selfY?: UiSelfAlignment;
  rootModifiers?: readonly UiModifier[];
}
interface CheckboxProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  label?: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
}
declare function Checkbox(props: Inputs<CheckboxProps>, ctx: ComponentContext): UiChild;
interface SwitchProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  label?: string;
  disabled?: boolean;
}
declare function Switch(props: Inputs<SwitchProps>, ctx: ComponentContext): UiChild;
interface RadioOption {
  readonly value: string;
  readonly label: string;
  readonly disabled?: boolean;
}
interface RadioGroupProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  options: readonly RadioOption[];
  label?: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
  direction?: 'row' | 'column';
}
declare function RadioGroup(props: Inputs<RadioGroupProps>, ctx: ComponentContext): UiChild;
interface TextInputProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  label?: string;
  placeholder?: string;
  description?: string;
  error?: string;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  multiline?: boolean;
  onSubmit?: () => void;
}
declare function TextInput(props: Inputs<TextInputProps>, ctx: ComponentContext): UiChild;
type TextAreaProps = Omit<TextInputProps, 'multiline'>;
declare function TextArea(props: Inputs<TextAreaProps>, ctx: ComponentContext): UiChild;
interface SliderProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  value?: number;
  defaultValue?: number;
  onChange?: (value: number) => void;
  min?: number;
  max?: number;
  step?: number;
  label?: string;
  disabled?: boolean;
  format?: (value: number) => string;
}
declare function Slider(props: Inputs<SliderProps>, ctx: ComponentContext): UiChild;
interface NumberInputProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  value?: number;
  defaultValue?: number;
  onChange?: (value: number) => void;
  min?: number;
  max?: number;
  step?: number;
  label?: string;
  error?: string;
  disabled?: boolean;
  required?: boolean;
}
declare function NumberInput(props: Inputs<NumberInputProps>, ctx: ComponentContext): UiChild;
interface CardProps extends ControlLayoutProps {
  title?: string;
  label?: string;
  padding?: number;
  children?: UiChild;
}
declare function Card(props: Inputs<CardProps>, _ctx: ComponentContext): UiChild;
interface DividerProps extends ControlLayoutProps {
  direction?: 'row' | 'column';
}
declare function Divider(props: Inputs<DividerProps>, _ctx: ComponentContext): UiChild;
interface ToolbarProps extends ControlLayoutProps {
  label?: string;
  children?: UiChild;
}
declare function Toolbar(props: Inputs<ToolbarProps>, _ctx: ComponentContext): UiChild;
interface TabDefinition {
  readonly value: string;
  readonly label: string;
  readonly disabled?: boolean;
}
interface TabsProps extends ControlLayoutProps {
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  tabs: readonly TabDefinition[];
  label?: string;
  children?: UiChild;
}
declare function Tabs(props: Inputs<TabsProps>, ctx: ComponentContext): UiChild;
interface AccordionSection {
  readonly value: string;
  readonly label: string;
  readonly content: UiChild;
  readonly disabled?: boolean;
}
interface AccordionProps extends ControlLayoutProps {
  open?: readonly string[];
  defaultOpen?: readonly string[];
  onOpenChange?: (open: readonly string[]) => void;
  sections: readonly AccordionSection[];
  exclusive?: boolean;
}
declare function Accordion(props: Inputs<AccordionProps>, _ctx: ComponentContext): UiChild;
interface SplitPaneProps extends ControlLayoutProps {
  split?: number;
  defaultSplit?: number;
  onSplitChange?: (split: number) => void;
  first?: UiChild;
  second?: UiChild;
  direction?: 'row' | 'column';
  min?: number;
  max?: number;
  label?: string;
}
declare function SplitPane(props: Inputs<SplitPaneProps>, ctx: ComponentContext): UiChild;
interface FindBarProps {
  inset?: number;
  placeholder?: string;
}
declare function FindBar(props: Inputs<FindBarProps>, ctx: ComponentContext): UiChild;
interface DialogProps {
  open?: boolean;
  onClose?: () => void;
  title?: string;
  description?: string;
  content?: UiChild;
  dismissible?: boolean;
  width?: number;
}
declare function Dialog(props: Inputs<DialogProps>, ctx: ComponentContext): UiChild;
interface OverlayHandle {
  readonly id: string;
  readonly open: Observable<boolean>;
  isOpen(): boolean;
  show(content: UiChild, options?: OverlayOptions): void;
  hide(): void;
}
interface OverlayOptions {
  readonly anchor?: UiNode | null;
  readonly placement?: OverlayPlacement;
  readonly offset?: number;
  readonly top?: number;
  readonly right?: number;
  readonly bottom?: number;
  readonly left?: number;
  readonly center?: 'x' | 'y' | 'both';
  readonly dismissOnOutsidePress?: boolean;
  readonly zIndex?: number;
  readonly environment?: UiNode | null;
  readonly onClose?: () => void;
}
declare function useOverlay(ctx: ComponentContext, name: string): OverlayHandle;
interface MenuItem {
  readonly value: string;
  readonly label: string;
  readonly disabled?: boolean;
}
interface MenuProps {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  anchor?: UiNode | null;
  items: readonly MenuItem[];
  onSelect?: (value: string) => void;
  placement?: OverlayPlacement;
  label?: string;
  at?: {
    readonly x: number;
    readonly y: number;
  };
}
declare function Menu(props: Inputs<MenuProps>, ctx: ComponentContext): UiChild;
interface SelectOption {
  readonly value: string;
  readonly label: string;
  readonly disabled?: boolean;
}
interface SelectProps extends ControlLayoutProps {
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  options: readonly SelectOption[];
  label?: string;
  placeholder?: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
  ref?: (node: UiNode | null) => void;
}
declare function Select(props: Inputs<SelectProps>, ctx: ComponentContext): UiChild;
interface TooltipProps {
  text?: string;
  placement?: OverlayPlacement;
  delay?: number;
  children?: UiChild;
}
declare function Tooltip(props: Inputs<TooltipProps>, ctx: ComponentContext): UiChild;
interface ToastProps {
  open?: boolean;
  onClose?: () => void;
  message?: string;
  tone?: 'info' | 'error';
  duration?: number;
  dismissible?: boolean;
}
declare function Toast(props: Inputs<ToastProps>, ctx: ComponentContext): UiChild;
interface LazyListProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  count: number;
  item: (index: number) => UiChild;
  estimatedItemExtent?: number;
  overscan?: number;
  itemKey?: (index: number) => string | number;
  revision?: unknown;
  selectedIndex?: number;
  defaultSelectedIndex?: number;
  onSelect?: (index: number) => void;
  onActivate?: (index: number) => void;
  label?: string;
}
declare function LazyList(props: Inputs<LazyListProps>, ctx: ComponentContext): UiChild;
interface DataColumn<T> {
  readonly key: string;
  readonly header: string;
  readonly width?: UiTrackSize;
  readonly compare?: (a: T, b: T) => number;
  readonly cell: (row: T, index: number) => UiChild;
  readonly align?: 'start' | 'center' | 'end';
}
interface DataTableSort {
  readonly column: string;
  readonly direction: 'ascending' | 'descending';
}
interface DataTableProps<T> extends ControlLayoutProps {
  ref?: UiNodeRef;
  columns: readonly DataColumn<T>[];
  rows: readonly T[];
  sort?: DataTableSort | null;
  defaultSort?: DataTableSort | null;
  onSortChange?: (sort: DataTableSort | null) => void;
  selectedRow?: number;
  defaultSelectedRow?: number;
  onSelect?: (index: number) => void;
  onActivate?: (index: number) => void;
  rowHeight?: number;
  columnGap?: number;
  label?: string;
}
declare function DataTable<T>(props: Inputs<DataTableProps<T>>, ctx: ComponentContext): UiChild;
interface TreeNode {
  readonly key: string;
  readonly label: string;
  readonly children?: readonly TreeNode[];
  readonly disabled?: boolean;
}
interface TreeProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  nodes: readonly TreeNode[];
  expanded?: readonly string[];
  defaultExpanded?: readonly string[];
  onExpandedChange?: (expanded: readonly string[]) => void;
  selectedKey?: string | null;
  defaultSelectedKey?: string | null;
  onSelect?: (key: string | null) => void;
  onActivate?: (key: string) => void;
  rowHeight?: number;
  label?: string;
}
declare function Tree(props: Inputs<TreeProps>, ctx: ComponentContext): UiChild;
interface ImageProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  src: string;
  alt?: string;
  objectFit?: ObjectFit;
  borderRadius?: number;
  placeholderColor?: never;
}
declare function Image(props: Inputs<ImageProps>, ctx: ComponentContext): UiChild;
interface VideoProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  src: string;
  alt?: string;
  objectFit?: ObjectFit;
  borderRadius?: number;
  loop?: boolean;
  autoplay?: boolean;
}
declare function Video(props: Inputs<VideoProps>, ctx: ComponentContext): UiChild;
interface IconProps extends ControlLayoutProps {
  ref?: UiNodeRef;
  path: string;
  viewBox?: number;
  size?: number;
  color?: UiColorValue;
  style?: 'fill' | 'stroke';
  strokeWidth?: number;
  fillRule?: 'nonzero' | 'evenodd';
  label?: string;
}
declare function Icon(props: Inputs<IconProps>, ctx: ComponentContext): UiChild;
interface SpinnerProps extends ControlLayoutProps {
  size?: number;
  label?: string;
  color?: UiColorValue;
}
declare function Spinner(props: Inputs<SpinnerProps>, ctx: ComponentContext): UiChild;
interface ProgressBarProps extends ControlLayoutProps {
  value?: number;
  min?: number;
  max?: number;
  label?: string;
  thickness?: number;
}
declare function ProgressBar(props: Inputs<ProgressBarProps>, ctx: ComponentContext): UiChild;
interface VirtualList {
  readonly windowRef: (window: UiVirtualWindow) => void;
  readonly ref: UiNodeRef;
  readonly viewport: UiModifier;
  readonly scrollY: Observable<number>;
  setLead(extent: number): void;
  reveal(index: number): void;
}
declare function virtualList(): VirtualList;
declare function stepIndex(current: number, by: number, count: number): number;
interface ControlledValue<T> {
  readonly value: Observable<T>;
  current(): T;
  change(next: T): void;
}
interface ControlledOptions<T> {
  readonly component: string;
  readonly name: string;
  readonly source: InputCell<T | undefined>;
  readonly initial: InputCell<T | undefined>;
  readonly fallback: T;
  readonly onChange: InputCell<((next: T) => void) | undefined>;
}
declare function controlled<T>(options: ControlledOptions<T>): ControlledValue<T>;
interface ControlFocus {
  readonly ref: UiNodeRef;
  readonly focused: Observable<boolean>;
  node(): UiNode | null;
  focus(): void;
}
declare function trackFocus(ctx: ComponentContext, forwarded?: InputCell<UiNodeRef | undefined>): ControlFocus;
export {
  Accordion,
  Card,
  Checkbox,
  controlled,
  DataTable,
  Dialog,
  Divider,
  FindBar,
  Icon,
  Image,
  keymap,
  LazyList,
  Menu,
  NumberInput,
  ProgressBar,
  quantize,
  RadioGroup,
  Select,
  Slider,
  Spinner,
  SplitPane,
  stepIndex,
  Switch,
  Tabs,
  TextArea,
  TextInput,
  Toast,
  Toolbar,
  Tooltip,
  trackFocus,
  Tree,
  type AccordionProps,
  type AccordionSection,
  type CardProps,
  type CheckboxProps,
  type ControlFocus,
  type ControlLayoutProps,
  type ControlledValue,
  type DataColumn,
  type DataTableProps,
  type DataTableSort,
  type DialogProps,
  type DividerProps,
  type FindBarProps,
  type IconProps,
  type ImageProps,
  type Keymap,
  type LazyListProps,
  type MenuItem,
  type MenuProps,
  type NumberInputProps,
  type OverlayHandle,
  type OverlayOptions,
  type ProgressBarProps,
  type RadioGroupProps,
  type RadioOption,
  type SelectOption,
  type SelectProps,
  type SliderProps,
  type SpinnerProps,
  type SplitPaneProps,
  type SwitchProps,
  type TabDefinition,
  type TabsProps,
  type TextAreaProps,
  type TextInputProps,
  type ToastProps,
  type ToolbarProps,
  type TooltipProps,
  type TreeNode,
  type TreeProps,
  type VideoProps,
  type VirtualList,
  useOverlay,
  Video,
  virtualList
};
