// API report for @gesso/testing.
//
// Generated by `pnpm api:update` from the declarations tsdown emits, with
// comments stripped and chunk hashes normalised. Committed so that a change
// to the public surface is a reviewable diff. Do not edit by hand.

// ==== index.d.ts ====
import {
  LayoutBox,
  LayoutExplanation,
  UiKeyModifiers,
  UiManualFrameClock,
  UiNode,
  UiRole,
  UiSemanticsMap,
  UiSemanticsRecord,
  UiSemanticState
} from "@gesso/core";
import {
  RecordedCall
} from "@gesso/core/testing";
import {
  ChannelReplica,
  ChannelToken,
  FrameMetrics,
  FrameworkChild,
  GessoRuntime,
  GessoRuntimeOptions,
  ServedChannel
} from "@gesso/framework";
interface PointAt {
  x?: number;
  y?: number;
  modifiers?: Partial<UiKeyModifiers>;
}
interface FireEvent {
  click(node: UiNode, at?: PointAt): void;
  pressDown(node: UiNode, at?: PointAt): void;
  pressUp(node: UiNode, at?: PointAt): void;
  pan(node: UiNode, x: number, y: number): void;
  pointerDown(x: number, y: number, options?: {
    buttons?: number;
    modifiers?: Partial<UiKeyModifiers>;
  }): void;
  pointerMove(x: number, y: number, options?: {
    buttons?: number;
    modifiers?: Partial<UiKeyModifiers>;
  }): void;
  pointerUp(x: number, y: number, options?: {
    buttons?: number;
    modifiers?: Partial<UiKeyModifiers>;
  }): void;
  wheel(options: {
    x?: number;
    y?: number;
    deltaX?: number;
    deltaY?: number;
    modifiers?: Partial<UiKeyModifiers>;
  }): void;
  keyDown(key: string, modifiers?: Partial<UiKeyModifiers>): void;
  keyUp(key: string, modifiers?: Partial<UiKeyModifiers>): void;
  press(key: string, modifiers?: Partial<UiKeyModifiers>): void;
  focus(node: UiNode): boolean;
  blur(): void;
  tab(): boolean;
  shiftTab(): boolean;
  type(text: string): void;
  paste(text: string): void;
}
declare function createFireEvent(runtime: GessoRuntime): FireEvent;
type TextMatch = string | RegExp;
interface RoleQueryOptions {
  name?: TextMatch;
  states?: readonly UiSemanticState[];
  disabled?: boolean;
}
interface Queries {
  getByRole(role: UiRole, options?: RoleQueryOptions): UiNode;
  queryByRole(role: UiRole, options?: RoleQueryOptions): UiNode | null;
  getAllByRole(role: UiRole, options?: RoleQueryOptions): UiNode[];
  findByRole(role: UiRole, options?: RoleQueryOptions & {
    maxFrames?: number;
  }): Promise<UiNode>;
  getByLabel(name: TextMatch): UiNode;
  queryByLabel(name: TextMatch): UiNode | null;
  getAllByLabel(name: TextMatch): UiNode[];
  findByLabel(name: TextMatch, options?: {
    maxFrames?: number;
  }): Promise<UiNode>;
  getByText(text: TextMatch): UiNode;
  queryByText(text: TextMatch): UiNode | null;
  getAllByText(text: TextMatch): UiNode[];
  findByText(text: TextMatch, options?: {
    maxFrames?: number;
  }): Promise<UiNode>;
  allNodes(): UiNode[];
  textOf(node?: UiNode): string[];
}
declare function nodesUnder(root: UiNode): UiNode[];
declare function textProperty(node: UiNode): string | undefined;
interface RenderedBase {
  readonly runtime: GessoRuntime;
  readonly clock: UiManualFrameClock;
  readonly frames: readonly FrameMetrics[];
  readonly draws: readonly RecordedCall[];
  readonly fireEvent: FireEvent;
  frame(time?: number): void;
  settle(options?: {
    maxFrames?: number;
  }): Promise<void>;
  getLayout(node: UiNode): LayoutBox;
  explain(node: UiNode): LayoutExplanation;
  explainText(node: UiNode): string;
  getSemantics(node: UiNode): UiSemanticsRecord;
  querySemantics(node: UiNode): UiSemanticsRecord | null;
  semanticsTree(): UiSemanticsMap;
  debug(node?: UiNode): string;
  clearDraws(): void;
  unmount(): void;
}
type Rendered = RenderedBase & Queries;
interface RenderTestOptions extends Omit<Partial<GessoRuntimeOptions>, 'root' | 'canvas' | 'clock'> {
  autoFrame?: boolean;
  onCreate?: (runtime: GessoRuntime) => void;
}
declare function renderTest(root: FrameworkChild, options?: RenderTestOptions): Rendered;
declare function formatTree(runtime: GessoRuntime, root: UiNode): string;
declare function renderedFor(node: UiNode): Rendered | null;
interface ServedForTest {
  get<V extends object, C extends object>(token: ChannelToken<V, C>): ChannelReplica<V, C>;
  settle(until?: () => boolean, timeoutMs?: number): Promise<void>;
  readonly errors: readonly string[];
  dispose(): void;
}
declare function serveForTest(channels: readonly ServedChannel[]): ServedForTest;
export {
  createFireEvent,
  formatTree,
  nodesUnder,
  renderedFor,
  renderTest,
  serveForTest,
  textProperty,
  type FireEvent,
  type PointAt,
  type Queries,
  type Rendered,
  type RenderedBase,
  type RenderTestOptions,
  type RoleQueryOptions,
  type ServedForTest,
  type TextMatch
};
// ==== matchers.d.ts ====
import {
  LayoutBox,
  UiNode,
  UiRole,
  UiSemanticState
} from "@gesso/core";
interface MatcherResult {
  pass: boolean;
  message: () => string;
}
interface ExpectedSemantics {
  role?: UiRole;
  name?: string;
  states?: readonly UiSemanticState[];
  disabled?: boolean;
  value?: number;
}
declare const matchers: {
  toHaveBox(received: UiNode, expected: Partial<LayoutBox>): MatcherResult;
  toHaveText(received: UiNode, expected: string): MatcherResult;
  toHaveSemantics(received: UiNode, expected: ExpectedSemantics): MatcherResult;
  toHaveFocus(received: UiNode): MatcherResult;
};
interface GessoMatchers<R = unknown> {
  toHaveBox: (expected: Partial<LayoutBox>) => R;
  toHaveText: (expected: string) => R;
  toHaveSemantics: (expected: ExpectedSemantics) => R;
  toHaveFocus: () => R;
}
declare module 'vitest' {
  interface Matchers<T = any> extends GessoMatchers<T> {}
}
export {
  ExpectedSemantics,
  matchers
};
