/**
 * Refreshes the committed copy of the three Audius playlists behind the
 * transitions example.
 *
 * The playlists app shows this snapshot from its first frame and
 * whenever Audius does not answer, so it should be recent but need not
 * be current. Run it when a curated playlist changes hands, and commit
 * the result on its own.
 *
 *   pnpm exec vite-node scripts/snapshot-transitions.ts
 *
 * `vite-node` rather than `node`, because the client it imports lives in
 * the playground and imports its neighbours without extensions, as the
 * bundler resolves them.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { AudiusApi } from '../apps/playground/src/examples/transitions/AudiusApi.ts';
import { CURATED } from '../apps/playground/src/examples/transitions/Catalogue.ts';
import type { PlaylistView, TrackView } from '../apps/playground/src/examples/transitions/TransitionsContract.ts';

const OUT = resolve(import.meta.dirname, '../apps/playground/src/examples/transitions/snapshot.ts');

const api = new AudiusApi();
const playlists: PlaylistView[] = [];
const tracks: Record<string, readonly TrackView[]> = {};
for (const card of CURATED) {
  const result = await api.playlist(card.audiusId, card.id);
  if (result.tracks.length === 0) {
    throw new Error(`Playlist ${card.audiusId} for card ${card.id} has no playable tracks; re-curate it.`);
  }
  playlists.push(result.playlist);
  tracks[card.id] = result.tracks;
  console.log(
    `card ${card.id}: ${result.playlist.title} by ${result.playlist.curator.name}, ${result.tracks.length} tracks`
  );
}

const taken = new Date().toISOString().slice(0, 10);
const body = JSON.stringify({ playlists, tracks }, null, 2);
writeFileSync(
  OUT,
  `import type { PlaylistView, TrackView } from './TransitionsContract';

/**
 * The three playlists as Audius described them on ${taken}.
 *
 * Generated by \`scripts/snapshot-transitions.ts\`; do not edit by hand.
 * The channel starts on this so the first frame has real titles, and
 * the app falls back to it when Audius does not answer. See
 * \`Catalogue\` and \`docs/TRANSITIONS_ROADMAP.md\` D6.
 */
export const SNAPSHOT: {
  readonly playlists: readonly PlaylistView[];
  readonly tracks: Readonly<Record<string, readonly TrackView[]>>;
} = ${body};
`
);
console.log(`wrote ${OUT}`);
