// API report for @gesso/electrobun.
//
// Generated by `pnpm api:update` from the declarations tsdown emits, with
// comments stripped and chunk hashes normalised. Committed so that a change
// to the public surface is a reviewable diff. Do not edit by hand.

// ==== frames.d.ts ====
declare const DEFAULT_CHUNK_BYTES = 1048576;
type GessoFrame = {
  readonly kind: 'open';
  readonly stream: number;
  readonly name: string;
} | {
  readonly kind: 'data';
  readonly stream: number;
  readonly body: string;
  readonly part?: number;
  readonly parts?: number;
} | {
  readonly kind: 'close';
  readonly stream: number;
};
declare function isGessoFrame(value: unknown): value is GessoFrame;
declare function frameData(stream: number, value: unknown, chunkBytes?: number): GessoFrame[];
declare class FrameAssembler {
  private readonly partial;
  take(frame: GessoFrame & {
    kind: 'data';
  }): unknown;
  forget(stream: number): void;
}
export {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  GessoFrame,
  isGessoFrame
};
// ==== index.d.ts ====
import {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  GessoFrame,
  isGessoFrame
} from "./frames-DsGY7d-I.js";
export {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  isGessoFrame,
  type GessoFrame
};
// ==== main.d.ts ====
import {
  GessoFrame
} from "./frames-DsGY7d-I.js";
import {
  ServedChannel
} from "@gesso/framework";
interface ChannelHostOptions {
  send: (frame: GessoFrame) => void;
  chunkBytes?: number;
}
interface ChannelHost {
  receive(frame: GessoFrame): void;
  dispose(): void;
}
declare function serveChannelsToWindow(channels: readonly ServedChannel[], options: ChannelHostOptions): ChannelHost;
export {
  ChannelHost,
  ChannelHostOptions,
  serveChannelsToWindow
};
// ==== view.d.ts ====
import {
  GessoFrame
} from "./frames-DsGY7d-I.js";
import {
  AppLogicEndpoint
} from "@gesso/framework";
interface ElectrobunBridgeOptions {
  send: (frame: GessoFrame) => void;
  chunkBytes?: number;
}
interface ElectrobunBridge {
  readonly endpoint: AppLogicEndpoint;
  receive(frame: GessoFrame): void;
  dispose(): void;
}
declare function createElectrobunBridge(options: ElectrobunBridgeOptions): ElectrobunBridge;
export {
  createElectrobunBridge,
  ElectrobunBridge,
  ElectrobunBridgeOptions
};
