// API report for @gesso/electrobun.
//
// Generated by `pnpm api:update` from the declarations tsdown emits, with
// comments stripped and chunk hashes normalised. Committed so that a change
// to the public surface is a reviewable diff. Do not edit by hand.

// ==== desktop.d.ts ====
import {
  GessoFrame
} from "./frames-Cb3vUTvQ.js";
import {
  ChannelToken,
  ServedChannel
} from "@gesso/framework";
import {
  Observable
} from "rxjs";
interface DesktopWindowTransport {
  send: (frame: GessoFrame) => void;
  close: () => void;
}
interface DesktopWindowHandle {
  readonly id: number;
  close(): void;
}
interface DesktopAppOptions {
  channels: readonly ServedChannel[] | ((window: DesktopWindowHandle) => readonly ServedChannel[]);
  open: (receive: (frame: GessoFrame) => void, window: DesktopWindowHandle) => DesktopWindowTransport;
  onOpenUrl?: (url: string, window: DesktopWindowHandle) => void;
  colorScheme?: Observable<'light' | 'dark'>;
  onLastWindowClosed?: () => void;
  chunkBytes?: number;
}
interface DesktopApp {
  openWindow(): DesktopWindowHandle;
  readonly windows: readonly DesktopWindowHandle[];
  readonly windowCount: Observable<number>;
  dispose(): void;
}
declare function createDesktopApp(options: DesktopAppOptions): DesktopApp;
interface DesktopWindowsView {
  count: number;
  id: number;
}
interface DesktopWindowsCommands {
  open: () => void;
  closeThis: () => void;
}
declare const DesktopWindows: ChannelToken<DesktopWindowsView, DesktopWindowsCommands>;
declare function windowsChannel(app: DesktopApp, window: DesktopWindowHandle): ServedChannel;
export {
  createDesktopApp,
  DesktopApp,
  DesktopAppOptions,
  DesktopWindowHandle,
  DesktopWindows,
  DesktopWindowsCommands,
  DesktopWindowsView,
  DesktopWindowTransport,
  windowsChannel
};
// ==== frames.d.ts ====
declare const DEFAULT_CHUNK_BYTES = 1048576;
type GessoFrame = {
  readonly kind: 'open';
  readonly stream: number;
  readonly name: string;
} | {
  readonly kind: 'data';
  readonly stream: number;
  readonly body: string;
  readonly part?: number;
  readonly parts?: number;
} | {
  readonly kind: 'close';
  readonly stream: number;
} |
{
  readonly kind: 'control';
  readonly name: string;
  readonly body: string;
};
declare function isGessoFrame(value: unknown): value is GessoFrame;
declare function frameData(stream: number, value: unknown, chunkBytes?: number): GessoFrame[];
declare class FrameAssembler {
  private readonly partial;
  take(frame: GessoFrame & {
    kind: 'data';
  }): unknown;
  forget(stream: number): void;
}
export {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  GessoFrame,
  isGessoFrame
};
// ==== index.d.ts ====
import {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  GessoFrame,
  isGessoFrame
} from "./frames-Cb3vUTvQ.js";
export {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  isGessoFrame,
  type GessoFrame
};
// ==== main.d.ts ====
import {
  GessoFrame
} from "./frames-Cb3vUTvQ.js";
import {
  ServedChannel
} from "@gesso/framework";
interface ChannelHostOptions {
  send: (frame: GessoFrame) => void;
  chunkBytes?: number;
  onOpenUrl?: (url: string) => void;
}
interface ChannelHost {
  receive(frame: GessoFrame): void;
  setColorScheme(scheme: 'light' | 'dark'): void;
  dispose(): void;
}
declare function serveChannelsToWindow(channels: readonly ServedChannel[], options: ChannelHostOptions): ChannelHost;
export {
  ChannelHost,
  ChannelHostOptions,
  serveChannelsToWindow
};
// ==== view.d.ts ====
import {
  GessoFrame
} from "./frames-Cb3vUTvQ.js";
import {
  AppLogicEndpoint
} from "@gesso/framework";
interface ElectrobunBridgeOptions {
  send: (frame: GessoFrame) => void;
  chunkBytes?: number;
  onColorScheme?: (scheme: 'light' | 'dark') => void;
}
interface ElectrobunBridge {
  readonly endpoint: AppLogicEndpoint;
  receive(frame: GessoFrame): void;
  openUrl(url: string): void;
  dispose(): void;
}
declare function createElectrobunBridge(options: ElectrobunBridgeOptions): ElectrobunBridge;
export {
  createElectrobunBridge,
  ElectrobunBridge,
  ElectrobunBridgeOptions
};
