// API report for gesso-electrobun.
//
// Generated by `pnpm api:update` from the declarations tsdown emits, with
// comments stripped and chunk hashes normalised. Committed so that a change
// to the public surface is a reviewable diff. Do not edit by hand.

// ==== desktop.d.ts ====
import {
  GessoFrame
} from "./frames.js";
import {
  ScreenAgentMessage,
  withWindowRoute
} from "./view.js";
import {
  AgentConfirmation,
  AgentSurface,
  AgentSurfaceLike,
  McpHandlerOptions
} from "gesso-framework/agent";
import {
  ChannelToken,
  ServedChannel
} from "gesso-framework";
import {
  Observable
} from "rxjs";
interface ScreenAgent {
  readonly surface: AgentSurfaceLike;
  attach(send: (message: ScreenAgentMessage) => void): {
    receive(message: ScreenAgentMessage): void;
    detach(): void;
  };
}
declare function createScreenAgent(): ScreenAgent;
type DesktopServe = (options: {
  hostname: string;
  port: number;
  fetch: (request: Request) => Promise<Response>;
}) => {
  stop(closeActiveConnections?: boolean): void;
};
interface DesktopAgentOptions extends Omit<McpHandlerOptions, 'allowedOrigins'> {
  port?: number;
  hostname?: string;
  confirm?: (request: AgentConfirmation) => boolean | Promise<boolean>;
  serve?: DesktopServe;
  screen?: AgentSurfaceLike;
}
interface DesktopAgent {
  readonly url: string;
  readonly surface: AgentSurface;
  stop(): void;
}
declare function serveDesktopAgent(channels: readonly ServedChannel[], options?: DesktopAgentOptions): DesktopAgent;
type ShowMessageBox = (options: {
  type?: 'info' | 'warning' | 'error' | 'question';
  title?: string;
  message?: string;
  detail?: string;
  buttons?: string[];
  defaultId?: number;
  cancelId?: number;
}) => Promise<{
  response: number;
}>;
declare function messageBoxConfirm(showMessageBox: ShowMessageBox): (request: AgentConfirmation) => Promise<boolean>;
interface DesktopWindowTransport {
  send: (frame: GessoFrame) => void;
  close: () => void;
}
interface DesktopWindowHandle {
  readonly id: number;
  readonly route: string | null;
  close(): void;
}
interface DesktopWindowOptions {
  readonly route?: string;
}
interface DesktopAppOptions {
  channels: readonly ServedChannel[] | ((window: DesktopWindowHandle) => readonly ServedChannel[]);
  open: (receive: (frame: GessoFrame) => void, window: DesktopWindowHandle) => DesktopWindowTransport;
  onOpenUrl?: (url: string, window: DesktopWindowHandle) => void;
  onOpenRoute?: (url: string, window: DesktopWindowHandle) => void;
  colorScheme?: Observable<'light' | 'dark'>;
  onLastWindowClosed?: () => void;
  chunkBytes?: number;
}
interface DesktopApp {
  openWindow(options?: DesktopWindowOptions): DesktopWindowHandle;
  readonly windows: readonly DesktopWindowHandle[];
  readonly windowCount: Observable<number>;
  dispose(): void;
}
declare function createDesktopApp(options: DesktopAppOptions): DesktopApp;
interface DesktopWindowsView {
  count: number;
  id: number;
}
interface DesktopWindowsCommands {
  open: () => void;
  closeThis: () => void;
}
declare const DesktopWindows: ChannelToken<DesktopWindowsView, DesktopWindowsCommands>;
declare function windowsChannel(app: DesktopApp, window: DesktopWindowHandle): ServedChannel;
export {
  createDesktopApp,
  createScreenAgent,
  DesktopApp,
  DesktopAppOptions,
  DesktopWindowHandle,
  DesktopWindowOptions,
  DesktopWindows,
  DesktopWindowsCommands,
  DesktopWindowsView,
  DesktopWindowTransport,
  messageBoxConfirm,
  serveDesktopAgent,
  type DesktopAgent,
  type DesktopAgentOptions,
  type DesktopServe,
  type ScreenAgent,
  type ShowMessageBox,
  windowsChannel,
  withWindowRoute
};
// ==== frames.d.ts ====
import {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  GessoFrame,
  isGessoFrame
} from "gesso-framework/remote";
export {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  GessoFrame,
  isGessoFrame
};
// ==== index.d.ts ====
import {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  GessoFrame,
  isGessoFrame
} from "./frames.js";
export {
  DEFAULT_CHUNK_BYTES,
  FrameAssembler,
  frameData,
  isGessoFrame,
  type GessoFrame
};
// ==== main.d.ts ====
import {
  RemoteChannelHost,
  RemoteChannelHostOptions
} from "gesso-framework/remote";
import {
  ServedChannel
} from "gesso-framework";
type ChannelHostOptions = RemoteChannelHostOptions;
type ChannelHost = RemoteChannelHost;
declare const serveChannelsToWindow: (channels: readonly ServedChannel[], options: ChannelHostOptions) => ChannelHost;
export {
  ChannelHost,
  ChannelHostOptions,
  serveChannelsToWindow
};
// ==== view.d.ts ====
import {
  RemoteBridge,
  RemoteBridgeOptions
} from "gesso-framework/remote";
declare function withWindowRoute(viewUrl: string, route: string | null | undefined): string;
declare function windowRoute(hash?: string): string;
type ElectrobunBridgeOptions = RemoteBridgeOptions;
type ElectrobunBridge = RemoteBridge;
declare const createElectrobunBridge: (options: ElectrobunBridgeOptions) => ElectrobunBridge;
type ScreenAgentMessage = unknown;
declare function relayScreenAgent(app: {
  openRenderPort(key: string): MessagePort | undefined;
}, send: (message: ScreenAgentMessage) => void): (message: ScreenAgentMessage) => void;
export {
  createElectrobunBridge,
  ElectrobunBridge,
  ElectrobunBridgeOptions,
  relayScreenAgent,
  ScreenAgentMessage,
  windowRoute,
  withWindowRoute
};
// ==== view.d.ts ====
import {
  createElectrobunBridge,
  ElectrobunBridge,
  ElectrobunBridgeOptions,
  relayScreenAgent,
  ScreenAgentMessage,
  windowRoute
} from "./view.js";
export {
  createElectrobunBridge,
  ElectrobunBridge,
  ElectrobunBridgeOptions,
  relayScreenAgent,
  ScreenAgentMessage,
  windowRoute
};
